// Package orchestrator provides the main orchestration logic for the Mini-Orca pipeline.
package orchestrator

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/nanaki-93/mini-orca/v2/internal/agent"
	"github.com/nanaki-93/mini-orca/v2/internal/config"
	"github.com/nanaki-93/mini-orca/v2/internal/llm"
	"github.com/nanaki-93/mini-orca/v2/internal/tools"
)

// Session represents a single execution session within the pipeline.
type Session struct {
	// ID is the unique identifier for this session.
	ID string
	// Phase is the current phase of the session.
	Phase Phase
	// Goal is the user's feature request.
	Goal string
	// ProjectPath is the path to the existing project.
	ProjectPath string
	// ProjectType is the type of the project.
	ProjectType string
	// CreatedAt is when the session was created.
	CreatedAt string
	// GeneratedCode is code generated by the coder.
	GeneratedCode string
	// TargetFile is the file where code was written.
	TargetFile string
}

// Orchestrator manages the execution flow of the multi-phase development pipeline.
type Orchestrator struct {
	llmClient      *llm.Client
	executor       tools.ToolExecutor
	config         *config.Config
	currentPhase   Phase
	currentSession *Session
	historyTracker *HistoryTracker
	ctx            context.Context
	cancel         context.CancelFunc
	humanGate      *HumanGate
}

// GetCurrentPhase returns the current phase.
func (o *Orchestrator) GetCurrentPhase() Phase {
	return o.currentPhase
}
func New(llmClient *llm.Client, executor tools.ToolExecutor, cfg *config.Config) *Orchestrator {
	ctx, cancel := context.WithCancel(context.Background())

	return &Orchestrator{
		llmClient: llmClient,
		executor:  executor,
		config:    cfg,
		ctx:       ctx,
		cancel:    cancel,
	}
}

// StartSession initializes a new session for a single feature request.
func (o *Orchestrator) StartSession(sessionID, goal, projectPath, projectType string) error {
	o.currentSession = &Session{
		ID: sessionID, Goal: goal, ProjectPath: projectPath,
		ProjectType: projectType, CreatedAt: time.Now().Format(time.RFC3339),
	}
	o.currentPhase = PhaseCoding
	logTransition("", PhaseCoding)
	return nil
}

// Run executes the full pipeline: coding → testing → review → human_gate
func (o *Orchestrator) Run() error {
	for {
		switch o.currentPhase {
		case PhaseCoding:
			if err := o.RunCoding(); err != nil {
				return fmt.Errorf("pipeline: coding failed: %w", err)
			}
		case PhaseTesting:
			if err := o.RunTesting(); err != nil {
				return fmt.Errorf("pipeline: testing failed: %w", err)
			}
		case PhaseReview:
			if err := o.RunReview(); err != nil {
				return fmt.Errorf("pipeline: review failed: %w", err)
			}
		case PhaseHumanReview:
			if err := o.RunHumanReview(); err != nil {
				return fmt.Errorf("pipeline: human review failed: %w", err)
			}
			if o.humanGate != nil && o.humanGate.IsApproved() {
				if err := o.transitionToCompleted(); err != nil {
					return fmt.Errorf("pipeline: completed failed: %w", err)
				}
				return nil
			}
			if o.humanGate != nil && !o.humanGate.IsApproved() {
				fmt.Printf("Human requested edits: %s\n", o.humanGate.Feedback())
				if err := o.transitionTo(PhaseCoding); err != nil {
					return fmt.Errorf("pipeline: failed to loop back to coding: %w", err)
				}
			}
		case "completed":
			return nil
		default:
			return fmt.Errorf("pipeline: unknown phase %s", o.currentPhase)
		}
	}
}

// RunCoding executes the coding phase of the pipeline.
func (o *Orchestrator) RunCoding() error {
	// Get project context
	projectContext, err := o.getProjectContext()
	if err != nil {
		return fmt.Errorf("coding phase: %w", err)
	}

	// Call coder agent
	var coderResult *agent.Result
	err = WithRetry(func() error {
		res, agentErr := o.runCoderAgent(o.currentSession.Goal, projectContext)
		if agentErr != nil {
			return fmt.Errorf("coder agent failed: %w", agentErr)
		}
		coderResult = res
		return nil
	}, o.config.Retry.MaxRetries, o.config.Retry.BackoffBase, o.config.Retry.BackoffMax)
	if err != nil {
		return fmt.Errorf("coding phase: coder execution failed: %w", err)
	}
	result := coderResult

	// Extract and write code
	code, targetFile, err := o.extractCodeFromResult(result.Output)
	if err != nil {
		return fmt.Errorf("coding phase: failed to extract code: %w", err)
	}
	if err := o.writeFileAtomic(targetFile, code); err != nil {
		return fmt.Errorf("coding phase: failed to write file: %w", err)
	}
	if err := o.formatCode(targetFile); err != nil {
		fmt.Printf("Warning: formatting failed for %s: %v\n", targetFile, err)
	}

	o.currentSession.GeneratedCode = code
	o.currentSession.TargetFile = targetFile

	// Transition to Testing
	if err := o.transitionTo(PhaseTesting); err != nil {
		return fmt.Errorf("coding phase: failed to transition: %w", err)
	}
	return nil
}

// getProjectContext retrieves the go.mod content from the project path.
func (o *Orchestrator) getProjectContext() (string, error) {
	if o.currentSession == nil || o.currentSession.ProjectPath == "" {
		return "", nil
	}
	goModPath := filepath.Join(o.currentSession.ProjectPath, "go.mod")
	if data, err := os.ReadFile(goModPath); err == nil {
		return string(data), nil
	}
	return "", nil
}

// runCoderAgent calls the coder agent with the user prompt and project context.
func (o *Orchestrator) runCoderAgent(userPrompt string, projectContext string) (*agent.Result, error) {
	orchestrator := agent.NewOrchestrator(o.llmClient, o.executor)
	return orchestrator.RunCoderFromPrompt(userPrompt, projectContext)
}

// extractCodeFromResult extracts code from the agent output and determines the target file.
func (o *Orchestrator) extractCodeFromResult(output string) (string, string, error) {
	if output == "" {
		return "", "", fmt.Errorf("empty code output")
	}
	codeBlocks := extractCodeBlocks(output)
	if len(codeBlocks) == 0 {
		return "", "", fmt.Errorf("no code blocks found in output")
	}
	code := codeBlocks[0].Content
	targetFile := o.determineTargetFileFromPrompt(code, codeBlocks[0].Language)
	return code, targetFile, nil
}

// determineTargetFileFromPrompt determines the target file from code comments or generates a default.
func (o *Orchestrator) determineTargetFileFromPrompt(code string, language string) string {
	lines := strings.Split(code, "\n")
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "// target:") {
			filePath := strings.TrimSpace(strings.TrimPrefix(line, "// target:"))
			if filePath != "" && o.currentSession != nil {
				return filepath.Join(o.currentSession.ProjectPath, filePath)
			}
		}
	}
	filename := fmt.Sprintf("feature_%d.go", time.Now().Unix())
	return filepath.Join(o.currentSession.ProjectPath, filename)
}

// writeFileAtomic writes content to a file atomically using temp file + rename.
func (o *Orchestrator) writeFileAtomic(path string, content string) error {
	// Create parent directories if needed
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("coding phase: failed to create directory %s: %w", dir, err)
	}

	// Create temp file in the same directory (same filesystem for atomic rename)
	tempFile, err := os.CreateTemp(dir, ".tmp-"+filepath.Base(path)+"-*")
	if err != nil {
		return fmt.Errorf("coding phase: failed to create temp file: %w", err)
	}
	tempPath := tempFile.Name()

	// Clean up temp file on error
	defer func() {
		if err != nil {
			os.Remove(tempPath)
		}
	}()

	// Write content to temp file
	if _, err := tempFile.WriteString(content); err != nil {
		tempFile.Close()
		return fmt.Errorf("coding phase: failed to write to temp file: %w", err)
	}

	// Close temp file before rename
	if err := tempFile.Close(); err != nil {
		return fmt.Errorf("coding phase: failed to close temp file: %w", err)
	}

	// Atomically rename temp file to target
	if err := os.Rename(tempPath, path); err != nil {
		return fmt.Errorf("coding phase: failed to rename temp file to %s: %w", path, err)
	}

	return nil
}

// formatCode formats the code file at the given path.
func (o *Orchestrator) formatCode(path string) error {
	if o.executor == nil {
		return fmt.Errorf("coding phase: executor not configured")
	}

	return o.executor.FormatCode(path)
}

// transitionTo transitions the pipeline to the specified phase.
func (o *Orchestrator) transitionTo(phase Phase) error {
	if err := ValidateTransition(o.currentPhase, phase); err != nil {
		return fmt.Errorf("transition: %w", err)
	}

	logTransition(o.currentPhase, phase)
	o.currentPhase = phase

	// Update session phase
	if o.currentSession != nil {
		o.currentSession.Phase = phase
	}

	return nil
}

// codeBlock represents a code block extracted from agent output.
type codeBlock struct {
	// Language is the programming language of the code block.
	Language string
	// Content is the actual code content.
	Content string
}

// extractCodeBlocks extracts code blocks from the agent output.
func extractCodeBlocks(output string) []codeBlock {
	var blocks []codeBlock

	// Split by triple backticks
	parts := strings.Split(output, "```")
	// parts[0] is text before first ```
	// parts[1] is content between first and second ```
	// ...
	for i := 1; i < len(parts); i += 2 {
		content := parts[i]
		lines := strings.SplitN(content, "\n", 2)
		language := "go"
		code := content
		if len(lines) > 1 {
			language = strings.TrimSpace(lines[0])
			code = lines[1]
		}
		if language == "" {
			language = "go"
		}
		blocks = append(blocks, codeBlock{
			Language: language,
			Content:  strings.TrimSpace(code),
		})
	}

	return blocks
}

// RunTesting executes the testing phase of the pipeline.
func (o *Orchestrator) RunTesting() error {
	if o.currentSession == nil || o.currentSession.GeneratedCode == "" {
		return fmt.Errorf("testing phase: no generated code available")
	}
	var testOutput string
	err := WithRetry(func() error {
		out, testErr := o.runTests()
		if testErr != nil {
			return fmt.Errorf("test execution failed: %w", testErr)
		}
		testOutput = out
		return nil
	}, 1, o.config.Retry.BackoffBase, o.config.Retry.BackoffMax)
	if err != nil {
		fmt.Printf("Warning: test execution returned error: %v\n", err)
	}

	var testerReport *TestReport
	err = WithRetry(func() error {
		res, agentErr := o.runTesterAgent(o.currentSession.GeneratedCode, testOutput)
		if agentErr != nil {
			return fmt.Errorf("tester agent failed: %w", agentErr)
		}
		testerReport = res
		return nil
	}, o.config.Retry.MaxRetries, o.config.Retry.BackoffBase, o.config.Retry.BackoffMax)
	if err != nil {
		return fmt.Errorf("testing phase: tester agent failed: %w", err)
	}
	report := testerReport

	if report.Passed {
		if err := o.transitionTo(PhaseReview); err != nil {
			return fmt.Errorf("testing phase: failed to transition to review: %w", err)
		}
	} else {
		if err := o.transitionTo(PhaseCoding); err != nil {
			return fmt.Errorf("testing phase: failed to transition to coding: %w", err)
		}
	}
	return nil
}

// runTests executes language-specific tests and captures the output.
func (o *Orchestrator) runTests() (string, error) {
	if o.executor == nil {
		return "", fmt.Errorf("testing phase: executor not configured")
	}

	// Execute tests using the tool executor
	result, err := o.executor.Execute("go", []string{"test", "./...", "-v", "-cover"}, 120*time.Second)
	if err != nil {
		// Capture whatever output we got even on error
		return result.Stdout, err
	}

	return result.Stdout, nil
}

// runTesterAgent calls the tester agent with code and test results for analysis.
func (o *Orchestrator) runTesterAgent(code string, testResults string) (*TestReport, error) {
	orchestrator := agent.NewOrchestrator(o.llmClient, o.executor)
	agentResult, err := orchestrator.RunTester(code, testResults)
	if err != nil {
		return nil, err
	}

	// Parse the agent result as a TestReport
	return parseTestReportFromAgentResult(agentResult)
}

// parseTestReportFromAgentResult parses an AgentResult into a TestReport.
func parseTestReportFromAgentResult(result *agent.Result) (*TestReport, error) {
	if result == nil {
		return nil, fmt.Errorf("parse test report: agent result is nil")
	}

	// Parse the agent result as a TestReport from JSON
	var report TestReport
	if err := json.Unmarshal([]byte(result.Output), &report); err != nil {
		// Fall back to creating a basic report from the output text
		report = TestReport{
			Summary: result.Output,
			Passed:  !strings.Contains(strings.ToLower(result.Output), "fail"),
		}
	}

	return &report, nil
}

// TestReport represents the output of a testing phase analysis by the tester agent.
type TestReport struct {
	Passed      bool     `json:"passed"`
	Failures    []string `json:"failures,omitempty"`
	Suggestions []string `json:"suggestions,omitempty"`
	Coverage    string   `json:"coverage,omitempty"`
	Summary     string   `json:"summary"`
}

// RunReview executes the review phase of the pipeline.
func (o *Orchestrator) RunReview() error {
	if o.currentSession == nil || o.currentSession.GeneratedCode == "" {
		return fmt.Errorf("review phase: no code available")
	}
	var reviewerReport *ReviewReport
	err := WithRetry(func() error {
		res, agentErr := o.runReviewerAgent(o.currentSession.GeneratedCode, o.currentSession.Goal)
		if agentErr != nil {
			return fmt.Errorf("reviewer agent failed: %w", agentErr)
		}
		reviewerReport = res
		return nil
	}, o.config.Retry.MaxRetries, o.config.Retry.BackoffBase, o.config.Retry.BackoffMax)
	if err != nil {
		return fmt.Errorf("review phase: reviewer agent failed: %w", err)
	}
	report := reviewerReport

	if o.isReviewPassing(report) {
		if err := o.transitionTo(PhaseHumanReview); err != nil {
			return fmt.Errorf("review phase: failed to transition to human review: %w", err)
		}
	} else {
		if err := o.transitionTo(PhaseCoding); err != nil {
			return fmt.Errorf("review phase: failed to transition to coding: %w", err)
		}
	}
	return nil
}

// runReviewerAgent calls the reviewer agent with code and user prompt for review.
func (o *Orchestrator) runReviewerAgent(code string, userPrompt string) (*ReviewReport, error) {
	orchestrator := agent.NewOrchestrator(o.llmClient, o.executor)
	agentResult, err := orchestrator.RunReviewer(code, userPrompt)
	if err != nil {
		return nil, err
	}
	return parseReviewReportFromAgentResult(agentResult)
}

// isReviewPassing determines if the review report indicates a passing review.
func (o *Orchestrator) isReviewPassing(report *ReviewReport) bool {
	// Pass if score is above threshold and no critical issues
	if report.Score >= 70 && len(report.Issues) == 0 {
		return true
	}

	// Also pass if recommendation indicates approval
	lowerRec := strings.ToLower(report.Recommendation)
	if strings.Contains(lowerRec, "approve") || strings.Contains(lowerRec, "pass") || strings.Contains(lowerRec, "accept") {
		return true
	}

	return false
}

// parseReviewReportFromAgentResult parses an AgentResult into a ReviewReport.
func parseReviewReportFromAgentResult(result *agent.Result) (*ReviewReport, error) {
	if result == nil {
		return nil, fmt.Errorf("parse review report: agent result is nil")
	}

	// Parse the agent result as a ReviewReport from JSON
	var report ReviewReport
	if err := json.Unmarshal([]byte(result.Output), &report); err != nil {
		// Fall back to creating a basic report from the output text
		report = ReviewReport{
			Summary: result.Output,
			Score:   50, // Default neutral score
		}
	}

	return &report, nil
}

// ReviewReport represents the output of a code review phase.
type ReviewReport struct {
	Issues         []string `json:"issues,omitempty"`
	Suggestions    []string `json:"suggestions,omitempty"`
	Score          int      `json:"score"`
	Recommendation string   `json:"recommendation"`
	Summary        string   `json:"summary"`
}

// RunHumanReview executes the human review phase of the pipeline.
func (o *Orchestrator) RunHumanReview() error {
	if o.currentSession == nil {
		return fmt.Errorf("human review phase: no session available")
	}
	code := o.currentSession.GeneratedCode
	if code == "" {
		return fmt.Errorf("human review phase: no code available")
	}

	var reviewSummary string

	o.humanGate = NewHumanGate(o.currentSession.ID, PhaseHumanReview)
	reviewOutput := o.formatHumanReviewOutput(code, reviewSummary)
	_, err := o.humanGate.RequestApproval(reviewOutput)
	if err != nil {
		return fmt.Errorf("human review phase: failed to get human response: %w", err)
	}
	return nil
}

// formatHumanReviewOutput formats the review package for human presentation.
func (o *Orchestrator) formatHumanReviewOutput(code string, reviewSummary string) string {
	var sb strings.Builder
	sb.WriteString("## Feature Implementation Review\n\n")
	sb.WriteString(fmt.Sprintf("**Session:** %s\n\n", o.currentSession.ID))
	sb.WriteString(fmt.Sprintf("**Feature Request:** %s\n\n", o.currentSession.Goal))
	sb.WriteString(fmt.Sprintf("**Generated At:** %s\n\n", time.Now().Format(time.RFC3339)))
	sb.WriteString(fmt.Sprintf("**Target File:** %s\n\n", o.currentSession.TargetFile))
	sb.WriteString("---\n\n## Generated Code\n\n```go\n")
	sb.WriteString(code)
	sb.WriteString("\n```\n\n")
	if reviewSummary != "" {
		sb.WriteString("## Automated Review Summary\n\n" + reviewSummary + "\n\n---\n\n")
	}
	sb.WriteString("Respond with: **approve** (complete) or **edit** (with feedback)\n")
	return sb.String()
}

// transitionToCompleted transitions the pipeline to the completed state.
func (o *Orchestrator) transitionToCompleted() error {
	if err := ValidateTransition(o.currentPhase, "completed"); err != nil {
		return fmt.Errorf("transition: %w", err)
	}
	logTransition(o.currentPhase, "completed")
	if o.currentSession != nil {
		o.currentSession.Phase = "completed"
	}
	o.currentPhase = "completed"
	return nil
}
