/* Offline design prototype. All project data and action outcomes below are fixtures. */
'use strict';

const iconPaths = {
  grid:'<rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/>',
  activity:'<path d="M3 12h4l3-8 4 16 3-8h4"/>',
  bug:'<rect x="7" y="7" width="10" height="13" rx="5"/><path d="M9 7V5a3 3 0 0 1 6 0v2M3 9h4m10 0h4M3 14h4m10 0h4M4 20l4-3m8 0 4 3M12 8v12"/>',
  gauge:'<path d="M4 18a9 9 0 1 1 16 0M6 18h12M12 13l5-6"/><circle cx="12" cy="13" r="1.5"/>',
  shield:'<path d="m12 3 8 3v6c0 4-3 7-8 9-5-2-8-5-8-9V6zM9 12l2 2 4-4"/>',
  code:'<path d="m8 5-6 7 6 7m8-14 6 7-6 7M14 3l-4 18"/>',
  terminal:'<path d="m4 6 6 6-6 6m9 0h7"/>',
  sparkles:'<path d="m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5L12 3ZM20 2v4m-2-2h4"/>',
  folder:'<path d="M3 7V5a2 2 0 0 1 2-2h5l2 3h7a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V7z"/>',
  search:'<circle cx="10" cy="10" r="6.5"/><path d="m15 15 6 6"/>',
  chevrons:'<path d="m8 8 4-4 4 4m-8 8 4 4 4-4"/>',
  chevron:'<path d="m9 5 7 7-7 7"/>',
  down:'<path d="m6 9 6 6 6-6"/>',
  arrow:'<path d="M4 12h16m-6-6 6 6-6 6"/>',
  upRight:'<path d="M6 18 18 6M6 6h12v12"/>',
  back:'<path d="M20 12H4m6-6-6 6 6 6"/>',
  branch:'<circle cx="6" cy="5" r="2"/><circle cx="6" cy="19" r="2"/><circle cx="18" cy="5" r="2"/><path d="M6 7v10m12-10c0 6-12 3-12 8"/>',
  ellipsis:'<circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/>',
  file:'<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8zM14 2v6h6M8 13h8m-8 4h5"/>',
  check:'<path d="m5 12 4 4L19 6"/>',
  circleCheck:'<circle cx="12" cy="12" r="9"/><path d="m8 12 3 3 5-6"/>',
  warning:'<path d="m12 3 10 18H2L12 3Zm0 6v5m0 3v1"/>',
  clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',
  refresh:'<path d="M20 7a9 9 0 0 0-15-1L2 9m0-6v6h6m-4 8a9 9 0 0 0 15 1l3-3m0 6v-6h-6"/>',
  play:'<path d="m7 4 14 8-14 8V4Z"/>',
  pause:'<path d="M8 4v16M16 4v16"/>',
  stop:'<rect x="5" y="5" width="14" height="14" rx="2"/>',
  close:'<path d="m6 6 12 12M6 18 18 6"/>',
  plus:'<path d="M12 4v16M4 12h16"/>',
  minus:'<path d="M4 12h16"/>',
  lock:'<rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3m-4 5v2"/>',
  cloud:'<path d="M6 18a5 5 0 0 1-1-10 7 7 0 0 1 13-1 5.5 5.5 0 0 1 0 11H6Z"/>',
  laptop:'<rect x="5" y="3" width="14" height="12" rx="2"/><path d="m5 15-3 5h20l-3-5M9 17h6"/>',
  send:'<path d="m3 3 19 9-19 9 4-9-4-9Zm4 9h15"/>',
  copy:'<rect x="8" y="8" width="12" height="13" rx="2"/><path d="M15 8V3H3v13h5"/>',
  layers:'<path d="m12 3 10 5-10 5L2 8l10-5ZM2 12l10 5 10-5M2 16l10 5 10-5"/>',
  sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1 1m12 12 1 1M5 19l1-1M18 6l1-1"/>',
  moon:'<path d="M20 14A9 9 0 0 1 10 3a9 9 0 1 0 10 11Z"/>',
  book:'<path d="M12 5C8 2 4 3 2 4v15c3-1 6-1 10 2 4-3 7-3 10-2V4c-2-1-6-2-10 1Zm0 0v16"/>',
  undo:'<path d="M4 4v7h7M4 11a8 8 0 1 1 1 8"/>',
  inbox:'<path d="m5 4-3 9v7h20v-7l-3-9H5ZM2 13h6l2 3h4l2-3h6"/>',
  globe:'<circle cx="12" cy="12" r="9"/><ellipse cx="12" cy="12" rx="4" ry="9"/><path d="M3 12h18"/>',
};
const icon = name => `<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">${iconPaths[name] || iconPaths.file}</svg>`;
const esc = value => String(value).replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const badge = (label, tone = '') => `<span class="badge ${tone}">${esc(label)}</span>`;
const button = (label, action, symbol = '', style = '', extra = '') => `<button class="button ${style}" data-action="${action}" ${extra}>${symbol ? icon(symbol) : ''}${label}</button>`;
const link = (label, route, symbol = '', style = '') => `<a class="button ${style}" href="#${route}">${symbol ? icon(symbol) : ''}${label}</a>`;
const textLink = (label, route) => `<a class="text-link" href="#${route}">${label}${icon('arrow')}</a>`;
const routes = [
  ['summary','Summary','Workspace','grid'],['welcome','Welcome','Workspace','folder'],['project','Project','Workspace','folder'],
  ['analysis','Analysis files','Analysis','activity'],['analysis-preview','Analysis preview','Analysis','play'],['analysis-run','Analysis run','Analysis','activity'],
  ['bugs','Bugs','Results','bug'],['bug-detail','Bug detail','Results','bug'],['performance','Performance','Results','gauge'],['performance-detail','Performance detail','Results','gauge'],['security','Security','Results','shield'],['security-detail','Security detail','Results','shield'],
  ['editor','Source','Editor','code'],['context','Context','Editor','layers'],['assistant','Assistant','Editor','sparkles'],['new-declaration','New declaration','Editor','plus'],['draft','Draft','Editor','code'],['checks','Checks','Editor','circleCheck'],['review','Review','Editor','layers'],['receipt','Apply & undo','Editor','check'],
  ['benchmark','Benchmark','Tools','gauge'],['terminal','Terminal','Tools','terminal'],['search','Search & commands','Tools','search'],['models','Models','Tools','sparkles'],['diagrams','Architecture & flows','Tools','layers'],['scan','Verified scan','Tools','shield'],['manifest','Context manifest','Tools','file'],['states','State gallery','Prototype','grid'],
];
const routeGroups = Object.groupBy ? Object.groupBy(routes, route => route[2]) : routes.reduce((acc, route) => ((acc[route[2]] ||= []).push(route), acc), {});
const files = [
  ['internal/cache/store.go','Current','Go',true],['internal/cache/store_test.go','Current','Go',true],['internal/api/server.go','Outdated','Go',true],['internal/api/middleware.go','Current','Go',true],['internal/api/handlers.go','Not analyzed','Go',true],['internal/config/config.go','Current','Go',true],['cmd/harbor/main.go','Current','Go',true],['internal/storage/local.go','Outdated','Go',true],['README.md','Current','Markdown',true],['docs/architecture.md','Current','Markdown',true],['go.mod','Current','Go module',true],['go.sum','Excluded','Go module',false],
  ...Array.from({length:13}, (_,i) => [`internal/service/${['auth','session','request','response','health','metrics','router','worker','queue','retry','backoff','shutdown','context'][i]}.go`,i < 10 ? 'Current' : i < 12 ? 'Outdated' : 'Not analyzed','Go',true]),
];
const findings = {
  bugs:[
    {title:'Expired entries are returned from the cache',path:'internal/cache/store.go',line:42,level:'High',origin:'AI suggestion',tone:'red',symbol:'Load'},
    {title:'Request body remains open on an early return',path:'internal/api/handlers.go',line:86,level:'Medium',origin:'AI suggestion',tone:'amber',symbol:'HandleRequest'},
    {title:'Retry loop drops the cancellation signal',path:'internal/service/retry.go',line:31,level:'Medium',origin:'AI suggestion',tone:'amber',symbol:'Retry'},
  ],
  performance:[
    {title:'Remove repeated parsing on cache hits',path:'internal/cache/store.go',line:56,level:'Medium',origin:'Unmeasured',tone:'blue',symbol:'Load'},
    {title:'Reuse the response buffer',path:'internal/api/server.go',line:104,level:'Low',origin:'Unmeasured',tone:'blue',symbol:'Serve'},
  ],
  security:[
    {title:'File path is not constrained to the project root',path:'internal/storage/local.go',line:63,level:'High',origin:'Source rule',tone:'red',symbol:'ReadFile'},
  ],
};
const originalCode = `package cache\n\nimport (\n    "sync"\n    "time"\n)\n\ntype Store struct {\n    mu      sync.RWMutex\n    entries map[string]Entry\n}\n\n// Load returns a cached value for key.\nfunc (s *Store) Load(key string) ([]byte, bool) {\n    s.mu.RLock()\n    defer s.mu.RUnlock()\n\n    entry, ok := s.entries[key]\n    if !ok {\n        return nil, false\n    }\n\n    return entry.Value, true\n}`;
const defaultDraft = `func (s *Store) Load(key string) ([]byte, bool) {\n    s.mu.RLock()\n    defer s.mu.RUnlock()\n\n    entry, ok := s.entries[key]\n    if !ok || time.Now().After(entry.ExpiresAt) {\n        return nil, false\n    }\n\n    return entry.Value, true\n}`;
const changeFixtures = {
  Load:{before:defaultDraft.replace(' || time.Now().After(entry.ExpiresAt)',''),after:defaultDraft,imports:'time',label:'Reject expired cache entries'},
  HandleRequest:{before:'func HandleRequest(client *http.Client, request *http.Request) error {\n    response, err := client.Do(request)\n    if err != nil {\n        return err\n    }\n    if response.StatusCode != http.StatusOK {\n        return ErrRequestFailed\n    }\n    defer response.Body.Close()\n    return nil\n}',after:'func HandleRequest(client *http.Client, request *http.Request) error {\n    response, err := client.Do(request)\n    if err != nil {\n        return err\n    }\n    defer response.Body.Close()\n    if response.StatusCode != http.StatusOK {\n        return ErrRequestFailed\n    }\n    return nil\n}',imports:'net/http',label:'Close the response body on every return path'},
  Retry:{before:'func Retry(ctx context.Context, request func() error, delay time.Duration) error {\n    for attempt := 0; attempt < 3; attempt++ {\n        if err := request(); err == nil {\n            return nil\n        }\n        <-time.After(delay)\n    }\n    return ErrRetryLimit\n}',after:'func Retry(ctx context.Context, request func() error, delay time.Duration) error {\n    for attempt := 0; attempt < 3; attempt++ {\n        if err := ctx.Err(); err != nil {\n            return err\n        }\n        if err := request(); err == nil {\n            return nil\n        }\n        select {\n        case <-ctx.Done():\n            return ctx.Err()\n        case <-time.After(delay):\n        }\n    }\n    return ErrRetryLimit\n}',imports:'context, time',label:'Respect cancellation while retrying'},
  ReadFile:{before:'func ReadFile(root, path string) ([]byte, error) {\n    fullPath := filepath.Join(root, path)\n    return os.ReadFile(fullPath)\n}',after:'func ReadFile(root, path string) ([]byte, error) {\n    if !filepath.IsLocal(path) {\n        return nil, errors.New("path outside project root")\n    }\n    fullPath := filepath.Join(root, path)\n    return os.ReadFile(fullPath)\n}',imports:'errors, os, path/filepath',label:'Reject paths outside the project root'},
};
function initialState() {
  return {originalDeclaration:defaultDraft.replace(' || time.Now().After(entry.ExpiresAt)',''),changeLabel:'Reject expired cache entries',sourceVersions:{},appliedBefore:'',newRequest:'',project:'harbor',scenario:'ready',fileQuery:'',fileFilter:'All files',selectedFiles:new Set(files.filter(f=>f[3]).map(f=>f[0])),findingQuery:'',findingFilter:'All',selectedFinding:{bugs:0,performance:0,security:0},draft:defaultDraft,imports:'time',validated:true,checks:true,draftDirty:false,applied:false,undone:false,runStatus:'Completed',runCount:24,runTotal:24,securityConsent:false,remoteConsent:false,request:'Handle expired cache entries without changing the method signature.',declarationName:'',declarationKind:'Function',editorFile:'internal/cache/store.go',symbol:'Load',diffMode:'Unified',benchmarkName:'BenchmarkCacheHit',benchmarkDone:false,scanDone:false,searchQuery:'',searchScope:'All',modelScope:'Analyze',zoom:100,diagram:'Architecture',terminalTabs:[{id:1,name:'zsh',lines:['harbor on main','❯ git status --short',' M internal/cache/store.go','']}],activeTerminal:1,terminalSequence:1,terminalOpen:false,explanation:false,toastTimer:null};
}
let state = initialState();
let route = 'summary';
let lastFocus = null;
let confirmAction = null;
let confirmGate = false;
const main = document.getElementById('main');
const dialog = document.getElementById('dialog');

function pageHeading(title, subtitle = '', actions = '', eyebrow = '') {
  return `<div class="page-heading"><div>${eyebrow ? `<div class="eyebrow">${eyebrow}</div>` : ''}<h1>${title}</h1>${subtitle ? `<p>${subtitle}</p>` : ''}</div><div class="heading-actions">${actions}</div></div>`;
}
function panel(title, body, action = '') { return `<section class="panel"><div class="panel-head"><h2>${title}</h2>${action}</div>${body}</section>`; }
function notice(message, tone='info', action='') { return `<div class="notice ${tone}" role="status">${icon(tone === 'error' ? 'warning' : 'clock')}<div>${message}</div>${action}</div>`; }
function meta(label,value) { return `<div class="meta-item"><span>${label}</span><strong>${value}</strong></div>`; }
function emptyState(title, message, action='', symbol='inbox') { return `<div class="panel empty">${icon(symbol)}<h2>${title}</h2><p>${message}</p>${action}</div>`; }
function stepper(current) { return `<nav class="stepper" aria-label="Change progress">${[['assistant','Request'],['draft','Draft'],['checks','Checks'],['review','Review'],['receipt','Applied']].map(([id,label],i)=>`<a href="#${id}" class="step ${i===current?'current':i<current?'done':''}" ${i===current?'aria-current="step"':''}><span class="step-number">${i<current?'✓':i+1}</span>${label}</a>`).join('')}</nav>`; }
function paintCode(line) {
  return line.split(/("(?:\\.|[^"\\])*"|\/\/.*$|\b(?:package|import|type|struct|func|return|if|defer|for|range|nil|true|false|var|make|select|case)\b)/g).map((part,index)=>index%2?`<span class="${part.startsWith('//')?'comment':part.startsWith('"')?'str':'kw'}">${esc(part)}</span>`:esc(part)).join('');
}
function sourceCode(code=originalCode, start=1, highlight=0) { return `<pre aria-label="Read-only source">${code.split('\n').map((line,i)=>`<span class="code-line ${i+start===highlight?'highlight':''}"><span class="line-no">${i+start}</span>${paintCode(line)}</span>`).join('')}</pre>`; }
function codePanel(path=state.editorFile, code=originalCode, start=1, highlight=0) { return `<div class="code-block"><div class="code-title"><span>${esc(path)}</span>${badge('Read-only')}</div>${sourceCode(code,start,highlight)}</div>`; }
function findingRow(category,index) {
  const f=findings[category][index];
  return `<a href="#${category==='bugs'?'bug-detail':category+'-detail'}" class="list-row" data-finding="${category}:${index}"><span class="finding-mark ${f.tone}">${icon(category==='bugs'?'bug':category==='performance'?'gauge':'shield')}</span><span class="list-copy"><strong>${f.title}</strong><small>${f.path}:${f.line} · ${f.origin}</small></span>${badge(f.level,f.tone)}${icon('chevron')}</a>`;
}
function diagramSvg(compact=false) {
  if(state.diagram==='Request flow' && !compact) return `<svg class="diagram" viewBox="0 0 680 300" role="img" aria-label="Request passes through router, handler, cache lookup and response"><path class="connector" d="M110 150h45m120 0h45m120 0h45"/><g>${[[10,'Request'],[165,'Router'],[320,'Cache'],[485,'Response']].map(([x,label])=>`<rect x="${x}" y="120" width="120" height="60" rx="8"/><text x="${x+60}" y="155" text-anchor="middle" class="node-label">${label}</text>`).join('')}</g><text class="edge-label" x="382" y="208" text-anchor="middle">hit → value · miss → storage</text></svg>`;
  return `<svg class="diagram" viewBox="0 0 680 290" role="img" aria-label="Harbor API connects to the service layer, which uses Cache and Storage. Configuration supplies the service."><path class="connector" d="M190 85h90m130 0h90M345 112v63m0 0H190v29m155-29h155v29"/><rect x="50" y="56" width="140" height="58" rx="8"/><rect class="primary-node" x="280" y="56" width="130" height="58" rx="8"/><rect x="500" y="56" width="130" height="58" rx="8"/><rect x="120" y="204" width="140" height="58" rx="8"/><rect x="430" y="204" width="140" height="58" rx="8"/><text x="120" y="90" text-anchor="middle" class="node-label">HTTP API</text><text x="345" y="90" text-anchor="middle" class="node-label">Service</text><text x="565" y="90" text-anchor="middle" class="node-label">Config</text><text x="190" y="239" text-anchor="middle" class="node-label">Cache</text><text x="500" y="239" text-anchor="middle" class="node-label">Storage</text><text x="230" y="71" class="edge-label" text-anchor="middle">request</text><text x="450" y="71" class="edge-label" text-anchor="middle">settings</text></svg>`;
}
function summaryPage() {
  const selected=files.filter(f=>state.selectedFiles.has(f[0]));
  const counts={current:selected.filter(f=>f[1]==='Current').length,outdated:selected.filter(f=>f[1]==='Outdated').length};
  counts.missing=selected.length-counts.current-counts.outdated;
  const percentage=selected.length?Math.round(counts.current/selected.length*100):0;
  const cards=[['Bugs',3,'bugs','bug','2 medium · 1 high'],['Performance',2,'performance','gauge','2 opportunities · unmeasured'],['Security',1,'security','shield','1 source-rule finding']];
  return `<div class="page">${pageHeading(esc(state.project),`Go service <span class="muted">/</span> 25 indexed files <span class="muted">/</span> main`,link('Review analysis','analysis-preview','play','primary')+link('Open editor','editor','code'),'PROJECT OVERVIEW')}
    <div class="overview-row"><div class="metric-grid" style="order:2">${cards.map(([label,count,id,symbol,caption])=>`<a href="#${id}" class="panel metric-card"><div class="metric-label"><span class="row">${icon(symbol)}${label}</span><span class="metric-arrow">${icon('upRight')}</span></div><div class="metric-number">${count}</div><div class="metric-caption">${caption}</div></a>`).join('')}</div>
    <section class="panel coverage-panel"><div class="coverage-ring"><svg viewBox="0 0 100 100" role="img" aria-label="${counts.current} of ${selected.length} selected files current"><circle class="ring-track" cx="50" cy="50" r="42"/><circle class="ring-mark" cx="50" cy="50" r="42" stroke-dasharray="${percentage*2.64} 264"/></svg><strong>${selected.length?percentage+'%':'—'}</strong></div><div><h2><a href="#analysis">Analysis coverage ${icon('upRight')}</a></h2><p>${selected.length?counts.current+' of '+selected.length+' selected files current':'No files selected'}</p><div class="legend"><span class="legend-item"><i class="legend-dot"></i>${counts.current} current</span><span class="legend-item"><i class="legend-dot amber"></i>${counts.outdated} outdated</span><span class="legend-item"><i class="legend-dot gray"></i>${counts.missing} not analyzed</span></div></div>${link('View files','analysis','arrow','small')}</section></div>
    <div class="grid two-columns section-gap">${panel('Needs attention',findings.bugs.map((_,i)=>findingRow('bugs',i)).join(''),textLink('All bugs','bugs'))}<section class="panel insight"><div class="row between"><h2>Engineering insight</h2>${badge('AI interpretation')}</div><p><strong>Keep expiry checks inside the cache.</strong> Callers currently receive values without knowing whether they are still valid.</p><p class="small">The API, service and storage layers have clear boundaries. Cache ownership is the next place to tighten.</p>${textLink('Explore context','context')}</section></div>
    <div class="grid two-columns section-gap">${panel('Architecture',`<div class="diagram-surface diagram-compact">${diagramSvg(true)}</div>`,textLink('Explore','diagrams'))}${panel('Packages',`<div class="table-wrap"><table><thead><tr><th>Package</th><th>Responsibility</th></tr></thead><tbody>${[['internal/api','HTTP & routing'],['internal/service','Request orchestration'],['internal/cache','In-memory cache'],['internal/storage','Local persistence']].map(([name,purpose])=>`<tr><td class="path">${name}</td><td class="secondary">${purpose}</td></tr>`).join('')}</tbody></table></div>`)}</div>
  </div>`;
}
function welcomePage() { return `<div class="page"><div class="welcome"><div class="brand-symbol" aria-hidden="true">◒</div><div class="eyebrow">YOUR NEXT GOOD CHANGE</div><h1>Start with a project.</h1><p>Understand the code. Make one deliberate change.</p><div class="actions">${button('Open project','open-project','folder','primary')}${link('Explore sample','summary','arrow','ghost')}</div><h2>RECENT PROJECTS</h2><div class="panel">${[['harbor','~/Developer/harbor','Go'],['atlas','~/Developer/atlas','Kotlin']].map(([name,path,type])=>`<button class="list-row" data-action="choose-project" data-project="${name}"><span class="project-avatar">${name[0].toUpperCase()}</span><span class="list-copy"><strong>${name}</strong><small>${path}</small></span>${badge(type)}${icon('chevron')}</button>`).join('')}</div></div></div>`; }
function projectPage() { return `<div class="page">${pageHeading('Project','Workspace settings and local inventory.',button('Switch project','open-project','folder'))}<div class="grid two-columns">${panel('Workspace',`<div class="detail-meta">${meta('Name',esc(state.project))}${meta('Location',`<code>~/Developer/${esc(state.project)}</code>`)}${meta('Branch','main')}${meta('Languages','Go · Markdown')}</div><div class="form-footer"><span class="small muted">25 indexed files</span>${button('Re-index','reindex','refresh','small')}</div>`)}${panel('Inventory',`<div class="detail-meta">${meta('Last indexed','Today, 10:42')}${meta('Revision','a82f1c9')}${meta('Selected for analysis',`${state.selectedFiles.size} files`)}${meta('Excluded','go.sum')}</div><div class="form-footer">${textLink('Manage files','analysis')}${button('View exclusions','exclusions','','small')}</div>`)}</div><div class="section-gap">${panel('Workspace actions',`<button class="list-row" data-action="close-project">${icon('folder')}<span class="list-copy"><strong>Close project</strong><small>Return to recent projects</small></span>${icon('chevron')}</button>`)}</div></div>`; }
function analysisLocked(){return ['Running','Paused'].includes(state.runStatus);}
function analysisPage() {
  return `<div class="page">${pageHeading('Analysis','Choose the files for your next run.',analysisLocked()?link('View current run','analysis-run','activity','primary'):link('Review analysis','analysis-preview','play','primary'))}<div class="tabs"><a href="#analysis" class="tab active">Files<span class="tab-count">25</span></a><a href="#analysis-run" class="tab">Run</a><a href="#scan" class="tab">Verified scan</a></div><div class="toolbar"><div class="input-wrap">${icon('search')}<label class="sr-only" for="file-search">Search files</label><input id="file-search" placeholder="Find a file…" value="${esc(state.fileQuery)}"></div><div class="filters">${['All files','Outdated','Excluded'].map(label=>`<button class="filter ${state.fileFilter===label?'active':''}" data-action="file-filter" data-value="${label}" aria-pressed="${state.fileFilter===label}">${label}</button>`).join('')}</div></div><div class="panel">${analysisLocked()?notice('File selection is locked for the current run.','',textLink('View run','analysis-run')):''}<div class="panel-head"><span class="small"><strong id="selected-count">${state.selectedFiles.size}</strong> <span class="muted">of 25 files selected</span></span><div class="actions">${button('Select all','select-all','','small ghost',analysisLocked()?'disabled':'')}${button('Clear','select-none','','small ghost',analysisLocked()?'disabled':'')}</div></div><div class="table-wrap"><table><thead><tr><th><span class="sr-only">Include</span></th><th>File</th><th>Language</th><th>Saved analysis</th></tr></thead><tbody id="file-rows">${fileRows()}</tbody></table></div></div></div>`;
}
function fileRows() { const matching=files.filter(([path,status])=>path.toLowerCase().includes(state.fileQuery.toLowerCase()) && (state.fileFilter==='All files'||state.fileFilter==='Excluded'&&!state.selectedFiles.has(path)||state.fileFilter==='Outdated'&&status==='Outdated'));return matching.map(([path,status,language])=>`<tr><td><input type="checkbox" data-file="${path}" aria-label="Include ${path}" ${state.selectedFiles.has(path)?'checked':''} ${analysisLocked()?'disabled':''}></td><td class="path"><a href="#editor" data-source="${path}">${path}</a></td><td class="secondary">${language}</td><td>${badge(state.selectedFiles.has(path)?status:'Excluded',state.selectedFiles.has(path)?status==='Current'?'green':status==='Outdated'?'amber':'':'')}</td></tr>`).join('') || '<tr><td colspan="4">No matching files.</td></tr>'; }
function previewPage() {
  return `<div class="page">${pageHeading('Ready to analyze?','Review the scope before starting.',link('Back to files','analysis','back','ghost'))}<div class="grid two-columns">${panel('Run scope',`<div class="detail-meta">${meta('Project',esc(state.project))}${meta('Selected files',String(state.selectedFiles.size))}${meta('Categories','Bugs · Performance · Security')}${meta('Request limit','Up to 30 model calls')}</div><div class="panel-body">${textLink('Inspect context','manifest')}</div>`)}${panel('Destinations',`<div class="settings-row"><span class="model-icon">${icon('laptop')}</span><div class="list-copy"><h3>Analyze</h3><p>Local model · localhost:11434</p></div>${badge('Local','green')}</div><div class="settings-row"><span class="model-icon">${icon('cloud')}</span><div class="list-copy"><h3>Security review</h3><p>Configured cloud provider</p></div>${badge('Remote','blue')}</div><div class="panel-body"><label class="checkbox-line"><input type="checkbox" id="analysis-remote" ${state.remoteConsent?'checked':''}>Allow selected source to be sent to this cloud provider.</label><label class="checkbox-line"><input type="checkbox" id="analysis-security" ${state.securityConsent?'checked':''}>Include AI security review.</label></div>`)}</div><div class="form-footer section-gap"><span class="small muted">${state.runStatus==='Paused'?'Resume with fresh consent':'No source changes'}</span>${button(state.runStatus==='Paused'?'Resume analysis':'Start analysis','start-analysis','play','primary',!state.remoteConsent||!state.securityConsent||!state.selectedFiles.size?'disabled':'')}</div>${!state.selectedFiles.size?notice('Select at least one file to continue.','',textLink('Choose files','analysis')):''}</div>`;
}
function runPage() {
  const status=state.scenario==='canceled'?'Canceled':state.scenario==='partial'?'Partial':state.scenario==='failed'?'Failed':state.runStatus;
  const running=status==='Running',paused=status==='Paused',finished=status==='Completed';
  const count=finished?state.runTotal:state.runCount;
  const actions=running?button('Pause','pause-run','pause')+button('Cancel','cancel-run','stop'):paused?link('Resume','analysis-preview','play','primary'):link('New analysis','analysis-preview','play','primary');
  return `<div class="page">${pageHeading('Analysis run',`${esc(state.project)} · ${state.runTotal} selected files`,actions)}<div class="tabs"><a href="#analysis" class="tab">Files</a><a href="#analysis-run" class="tab active">Run</a><a href="#scan" class="tab">Verified scan</a></div><section class="panel"><div class="run-overview"><div class="row"><span class="finding-mark ${running?'blue':''}">${icon(running?'activity':paused?'pause':'circleCheck')}</span><div><h2>${status}</h2><p class="small">${running?'Reviewing internal/cache/store.go':paused?'Run paused. Completed results are available.':finished?'All selected files processed.':'Completed results retained.'}</p></div></div><div class="run-stat">${count}<span class="number-unit">/ ${state.runTotal} files</span></div></div><div class="run-progress"><div class="row between"><span>${Math.round(count/Math.max(1,state.runTotal)*100)}% processed</span><span>Started 10:44 · 2m 18s elapsed</span></div><div class="progress-track"><div class="progress-fill" style="width:${Math.min(100,count/Math.max(1,state.runTotal)*100)}%"></div></div></div></section><div class="grid three-columns section-gap">${[['Bugs','bugs',3],['Performance','performance',2],['Security','security',1]].map(([name,id,n])=>`<a href="#${id}" class="panel panel-pad"><div class="row between"><h2>${name}</h2>${icon('upRight')}</div><div class="metric-number">${n}</div><span class="small muted">${name==='Security'?'1 source-rule finding':'Results available'}</span></a>`).join('')}</div><div class="section-gap">${panel('Activity',`${[['circleCheck','internal/api/middleware.go','Completed','10:46:18'],['circleCheck','internal/config/config.go','Completed','10:46:04'],['circleCheck','cmd/harbor/main.go','Completed','10:45:52'],['warning','internal/api/server.go','Partial · response limit','10:45:33']].map(([symbol,path,result,time])=>`<div class="activity-row">${icon(symbol)}<div><span class="mono small">${path}</span><p class="small muted">${result}</p></div><span class="time">${time}</span></div>`).join('')}`)}</div></div>`;
}

function resultsPage(category) {
  const name=category[0].toUpperCase()+category.slice(1), isPerf=category==='performance',isSecurity=category==='security';
  const tabs=isSecurity?['All','Source rule','AI suggestion']:isPerf?['All','Unmeasured','Benchmarked']:['All','High','Medium'];
  return `<div class="page">${pageHeading(name,isPerf?'Opportunities to measure.':isSecurity?'Source-rule findings and AI reviews.':'Findings from the latest analysis.',isPerf?link('Benchmarks','benchmark','gauge'):isSecurity?link('Run verified scan','scan','shield'):link('View analysis','analysis-run','activity'))}
    <div class="toolbar"><div class="filters">${tabs.map(label=>`<button class="filter ${state.findingFilter===label?'active':''}" data-action="finding-filter" data-value="${label}" aria-pressed="${state.findingFilter===label}">${label}${label==='All'?` <span class="tab-count">${findings[category].length}</span>`:''}</button>`).join('')}</div><div class="input-wrap">${icon('search')}<label class="sr-only" for="finding-search">Search ${name.toLowerCase()}</label><input id="finding-search" placeholder="Search findings…" value="${esc(state.findingQuery)}"></div></div><div class="panel" id="finding-rows">${resultRows(category)}</div>${isSecurity?`<div class="section-gap small muted">Latest source scan · today at 10:42 · 24 files</div>`:''}</div>`;
}
function resultRows(category) {
  const rows=findings[category].map((finding,index)=>({finding,index})).filter(({finding})=>`${finding.title} ${finding.path}`.toLowerCase().includes(state.findingQuery.toLowerCase()) && (state.findingFilter==='All'||finding.level===state.findingFilter||finding.origin===state.findingFilter));
  return rows.map(({index})=>findingRow(category,index)).join('') || `<div class="empty">${icon('search')}<h2>No matching findings</h2><p>Try another filter or search.</p>${button('Clear filters','clear-findings','','small')}</div>`;
}
function detailPage(category) {
  const f=findings[category][state.selectedFinding[category]],name=category[0].toUpperCase()+category.slice(1);
  const explanations={
    bugs:[['A cache hit can return an expired value.','Load checks that the key exists, but does not compare ExpiresAt with the current time. A caller can continue using stale data until another operation removes the entry.','Treat an expired entry as a cache miss. Keep the current lock and return signature.'],['An early return leaves the request body open.','The error path returns before the response body is closed. Repeated failures can retain connections longer than necessary.','Close the body immediately after checking the request error.'],['Cancellation does not reach the retry loop.','The retry delay waits on a timer without selecting on the request context. Canceled requests can keep retrying.','Select on context cancellation alongside the retry timer.']],
    performance:[['Cache hits parse a value that was already parsed at insertion.','The lookup path repeats decoding work. A stored representation could avoid those allocations for frequent cache hits.','Measure BenchmarkCacheHit before changing the stored representation.'],['Each response allocates a fresh buffer.','The handler creates a byte buffer for every request. Pooling may help under sustained load, at the cost of retained memory.','Measure allocations and latency before introducing a pool.']],
    security:[['A joined path may escape the configured root.','ReadFile joins an incoming path with the root without checking the resolved location. Parent segments could address a sibling directory.','Resolve the path, verify containment, then read the file.']],
  };
  const [lead,body,recommendation]=explanations[category][state.selectedFinding[category]];
  const snippet=category==='security'?`func ReadFile(root, path string) ([]byte, error) {\n    fullPath := filepath.Join(root, path)\n    return os.ReadFile(fullPath)\n}`:category==='performance'?`entry, ok := s.entries[key]\nif !ok {\n    return nil, false\n}\nreturn decode(entry.Raw), true`:state.selectedFinding.bugs===0?`entry, ok := s.entries[key]\nif !ok {\n    return nil, false\n}\nreturn entry.Value, true`:state.selectedFinding.bugs===1?`response, err := client.Do(request)\nif err != nil {\n    return err\n}\nif response.StatusCode != http.StatusOK {\n    return ErrRequestFailed\n}\ndefer response.Body.Close()`:`for attempt := 0; attempt < maxRetries; attempt++ {\n    if err := request(); err == nil {\n        return nil\n    }\n    <-time.After(delay)\n}`;
  return `<div class="page"><div class="row" style="margin-bottom:22px">${textLink(name,category)}</div>${pageHeading(esc(f.title),'',category==='performance'?link('Measure impact','benchmark','gauge','primary'):button('Prepare change','prepare-finding','sparkles','primary'),name.toUpperCase())}<div class="details-layout"><div><div class="detail-section"><div class="row wrap" style="margin-bottom:20px">${badge(f.level,f.tone)}${badge(f.origin)}${badge(state.scenario==='stale'?'Outdated':'Current',state.scenario==='stale'?'amber':'outline')}</div><h2>${lead}</h2><p>${body}</p></div><div class="detail-section"><h2>Evidence</h2>${codePanel(f.path,snippet,f.line,f.line+1)}</div><div class="detail-section"><h2>${category==='performance'?'What to measure':'Suggested change'}</h2><p>${recommendation}</p></div>${category==='security'?`<div class="detail-section"><h2>Rule</h2><p><code>path-outside-root</code> · Syntactic source finding</p></div>`:''}</div><aside><section class="panel detail-meta">${meta('Location',`<code>${f.path}:${f.line}</code>`)}${meta('Declaration',`<code>${f.symbol}</code>`)}${meta('Origin',f.origin)}${meta('Analysis','Today, 10:46')}${meta('Revision','a82f1c9')}</section><div class="actions section-gap">${button('Open source','finding-source','code')}${link('Context','context','layers')}</div></aside></div></div>`;
}
function selectedSource() {
  if(state.sourceVersions[state.editorFile])return state.sourceVersions[state.editorFile];
  if(state.editorFile==='internal/cache/store.go') return originalCode;
  const finding=Object.values(findings).flat().find(f=>f.path===state.editorFile&&changeFixtures[f.symbol]);
  if(finding)return `package ${state.editorFile.split('/').at(-2)}\n\n${changeFixtures[finding.symbol].before}`;
  if(state.editorFile==='README.md') return `# Harbor\n\nA small Go service with a local cache.\n\n## Packages\n\n- api: request routing\n- service: orchestration\n- cache: in-memory values\n- storage: local persistence`;
  if(state.editorFile==='go.mod') return `module example.com/harbor\n\ngo 1.22`;
  return `package ${state.editorFile.split('/').at(-2)||'main'}\n\n// Sample source preview.\nfunc ${esc(state.symbol)}() error {\n    return nil\n}`;
}
function editorPage() {
  return `<div class="editor-layout"><aside class="file-tree" aria-label="Project files"><div class="tree-title">Explorer</div><div class="tree-row">${icon('down')}${esc(state.project)}</div><div class="tree-row indent">${icon('folder')}internal</div>${['cache','api','storage'].map(dir=>`<div class="tree-row indent">${icon('down')}${dir}</div>${files.filter(f=>f[0].startsWith('internal/'+dir+'/')).map(([path])=>`<button class="tree-row indent2 ${state.editorFile===path?'selected':''}" data-action="source-file" data-path="${path}">${icon('file')}${path.split('/').at(-1)}</button>`).join('')}`).join('')}<div class="tree-row">${icon('folder')}cmd</div>${['README.md','go.mod'].map(path=>`<button class="tree-row ${state.editorFile===path?'selected':''}" data-action="source-file" data-path="${path}">${icon('file')}${path}</button>`).join('')}</aside><section class="editor-center"><div class="editor-tabs"><span class="editor-tab">${icon('file')}${esc(state.editorFile.split('/').at(-1))}</span><a class="editor-tab" href="#review">${icon('layers')}Review</a></div><div class="editor-crumb">${esc(state.editorFile)}<span>/</span><span class="symbol-chip">${state.symbol}</span><span style="margin-left:auto">${badge('Read-only')}</span></div><div class="editor-code">${sourceCode(selectedSource())}</div><div class="editor-footer"><span class="small muted">${state.editorFile.endsWith('.go')?'Go':'Text'} · UTF-8 · LF</span>${link('New declaration','new-declaration','plus','small')}</div></section><aside class="editor-aside"><div class="eyebrow">SELECTED DECLARATION</div><span class="symbol-chip">${icon('code')}${state.symbol}</span><h2>${state.symbol==='Load'?'Cache lookup':esc(state.symbol)}</h2><p>${state.symbol==='Load'?'Returns a cached value for a key.':'Inspect this declaration or request a focused change.'}</p>${link('View context','context','layers')}${link('Ask assistant','assistant','sparkles','primary')}<div class="symbol-list"><div class="eyebrow">SYMBOLS</div>${['Store','Load','Set','Delete'].map(name=>`<button class="${state.symbol===name?'selected':''}" data-action="select-symbol" data-value="${name}">${name==='Store'?'T':'ƒ'} ${name}</button>`).join('')}</div><div class="section-gap">${badge('1 related finding','amber')}<p style="margin-top:10px">${textLink('Expired cache entries','bug-detail')}</p></div></aside></div>`;
}
function contextPage() {
  return `<div class="page">${pageHeading('Context',`<code>${esc(state.editorFile)} / ${esc(state.symbol)}</code>`,link('Ask assistant','assistant','sparkles','primary'))}<div class="details-layout"><div><div class="panel"><div class="panel-head"><h2>${state.symbol}</h2>${badge('Declaration')}</div><div class="panel-body"><p class="small">Returns the cached value and whether the key was found.</p></div>${sourceCode(state.originalDeclaration)}</div><div class="grid equal-columns section-gap">${panel('Used by',`<a href="#editor" data-source="internal/api/handlers.go" class="list-row"><span class="list-copy"><strong>HandleRequest</strong><small>internal/api/handlers.go:52</small></span>${icon('chevron')}</a><a href="#editor" data-source="internal/service/health.go" class="list-row"><span class="list-copy"><strong>CheckHealth</strong><small>internal/service/health.go:28</small></span>${icon('chevron')}</a>`)}${panel('Related tests',`<a href="#editor" data-source="internal/cache/store_test.go" class="list-row"><span class="list-copy"><strong>TestStoreLoad</strong><small>Cache hit and missing key</small></span>${icon('chevron')}</a><a href="#benchmark" class="list-row"><span class="list-copy"><strong>BenchmarkCacheHit</strong><small>Cache-hit latency</small></span>${icon('chevron')}</a>`)}</div><div class="section-gap">${panel('Explanation',state.explanation?'<div class="panel-body"><p class="small">Load holds a read lock while looking up a key. It returns the entry value when present; expiry needs to be checked before returning.</p></div>':`<div class="panel-body">${button('Explain declaration','explain','sparkles')}</div>`,state.explanation?badge('AI interpretation'):'')}</div></div><aside><section class="panel detail-meta">${meta('Scope','One declaration')}${meta('Language','Go')}${meta('Source','Current · a82f1c9')}${meta('Context','3 files · 2.4 KB')}</section><div class="section-gap">${textLink('Inspect request context','manifest')}</div></aside></div></div>`;
}
function assistantPage() { return `<div class="page">${pageHeading('Make a change',`<code>${esc(state.editorFile)} / ${esc(state.symbol)}</code>`,link('Source','editor','code'))}${stepper(0)}<div class="details-layout"><div class="panel"><div class="panel-head"><h2>Assistant</h2>${badge('Function · cloud','blue')}</div><div class="conversation"><div class="message"><div class="author">${icon('sparkles')}Mini-Orca</div>What would you like to change in <code>${esc(state.symbol)}</code>?</div><div class="actions">${button('Handle expiry','prompt-expiry','','small')}${button('Simplify logic','prompt-simplify','','small')}${link('New declaration','new-declaration','plus','small')}</div></div><div class="composer"><label class="sr-only" for="request">Change request</label><textarea id="request" placeholder="Describe your change…">${esc(state.request)}</textarea><div class="composer-bar"><span class="small muted">${icon('code')} One declaration</span>${button('Prepare draft','prepare-draft','send','primary')}</div></div><details><summary>Constraints</summary><div class="panel-body"><label class="field-label" for="constraints">Additional constraints</label><input id="constraints" placeholder="e.g. Keep the public signature"></div></details></div><aside><section class="panel detail-meta">${meta('Target',`<code>${esc(state.symbol)}</code>`)}${meta('File',`<code>${esc(state.editorFile)}</code>`)}${meta('Destination','Configured cloud provider')}${meta('Context','3 files · 2.4 KB')}</section><div class="section-gap">${textLink('View context','manifest')}</div></aside></div></div>`; }
function newDeclarationPage() { return `<div class="page">${pageHeading('New declaration',`<code>${esc(state.editorFile)}</code>`,link('Back to editor','editor','back','ghost'))}${stepper(0)}<div class="details-layout"><section class="panel panel-pad"><div class="filters">${['Function','Type'].map(kind=>`<button class="filter ${state.declarationKind===kind?'active':''}" data-action="declaration-kind" data-value="${kind}" aria-pressed="${state.declarationKind===kind}">${kind}</button>`).join('')}</div><label class="field-label" for="declaration-name">${state.declarationKind} name</label><input id="declaration-name" placeholder="${state.declarationKind==='Type'?'CacheStats':'EvictExpired'}" value="${esc(state.declarationName)}" autocomplete="off"><label class="field-label" for="new-request">What should it do?</label><textarea id="new-request" rows="5" placeholder="Describe the behavior…">${esc(state.newRequest)}</textarea><div id="name-error" class="small" role="alert" style="color:var(--red);margin-top:12px"></div><div class="actions section-gap">${button('Prepare draft','prepare-new','sparkles','primary')}</div></section><aside><section class="panel detail-meta">${meta('Package','cache')}${meta('File',`<code>${esc(state.editorFile)}</code>`)}${meta('Destination','Configured cloud provider')}</section></aside></div></div>`; }
function draftPage() { return `<div class="page">${pageHeading('Draft',`<code>${esc(state.editorFile)} / ${esc(state.symbol)}</code>`,button('Discard','discard-draft','','ghost'))}${stepper(1)}<div class="details-layout"><section class="panel"><div class="panel-head"><h2>Proposed declaration</h2><span id="draft-badge">${badge(state.validated?'Validated':'Edited',state.validated?'green':'amber')}</span></div><label class="sr-only" for="draft-code">Editable declaration</label><textarea spellcheck="false" id="draft-code" class="draft-area">${esc(state.draft)}</textarea><div class="panel-body"><label class="field-label" for="imports">Required imports</label><input id="imports" class="mono" value="${esc(state.imports)}"></div><div class="form-footer"><span class="small muted">${icon('code')} Declaration only</span><div class="actions">${button('Validate','validate-draft','check')}${link('Continue to checks','checks','arrow','primary')}</div></div><div id="draft-error" role="alert"></div></section><aside><section class="panel detail-meta">${meta('Change',esc(state.changeLabel))}${meta('Target',`<code>${esc(state.symbol)}</code>`)}${meta('Source','Unchanged')}${meta('Evidence',state.checks?'Checks available':'Revalidation needed')}</section><div class="section-gap">${textLink('Compare with source','review')}</div></aside></div></div>`; }
function checksPage() {
  return `<div class="page">${pageHeading('Checks',`<code>${esc(state.editorFile)}</code>`,button(state.checks?'Run again':'Run checks','run-checks','play','primary',!state.validated?'disabled':''))}${stepper(2)}${!state.validated?notice('Validate the edited draft before running checks.','',textLink('Open draft','draft')):''}<div class="details-layout"><div class="panel"><div class="panel-head"><h2>${state.checks?'Checks passed':'Ready for checks'}</h2>${badge(state.checks?'3 / 3':'Not run',state.checks?'green':'')}</div>${[['Format & parse','gofmt · Go parser','0.1s'],['Scoped tests','go test ./internal/cache -run TestStoreLoad','0.8s'],['Static checks','go vet ./internal/cache','0.4s']].map(([name,command,duration])=>`<div class="check-row">${icon(state.checks?'circleCheck':'clock')}<div class="list-copy"><h3>${name}</h3><p><code>${command}</code></p></div><span class="check-time">${state.checks?duration:'—'}</span></div>`).join('')}<div class="form-footer"><span class="small muted">${state.checks?'Completed in a copied workspace':'Execution approval required'}</span>${link('Review change','review','arrow',state.checks?'primary':'')}</div></div><aside><section class="panel detail-meta">${meta('Draft',state.validated?'Validated':'Edited')}${meta('Source revision','a82f1c9')}${meta('Scope','internal/cache')}${meta('Result',state.checks?'Passed':'Not run')}</section></aside></div></div>`;
}
function draftDiff() {
  const before=state.originalDeclaration?state.originalDeclaration.split('\n'):[],after=state.draft.split('\n');
  let prefix=0,suffix=0;
  while(prefix<before.length&&prefix<after.length&&before[prefix]===after[prefix])prefix++;
  while(suffix<before.length-prefix&&suffix<after.length-prefix&&before[before.length-1-suffix]===after[after.length-1-suffix])suffix++;
  return {prefix,suffix,before,after,removed:before.slice(prefix,before.length-suffix),added:after.slice(prefix,after.length-suffix)};
}
function diffContent() {
  if(state.diffMode==='Split') return `<div class="split-diff"><div><div class="code-title">Original</div>${sourceCode(state.originalDeclaration,14)}</div><div><div class="code-title">Draft</div>${sourceCode(state.draft,14)}</div></div>`;
  const diff=draftDiff();
  const row=(line,type,number)=>`<span class="code-line ${type}"><span class="line-no">${number}</span>${paintCode(line)}</span>`;
  return `<pre aria-label="Read-only composed diff">${diff.before.slice(0,diff.prefix).map((line,i)=>row(line,'',i+14)).join('')}${diff.removed.map(line=>row(line,'remove','−')).join('')}${diff.added.map(line=>row(line,'add','+')).join('')}${diff.after.slice(diff.after.length-diff.suffix).map((line,i)=>row(line,'',14+diff.after.length-diff.suffix+i)).join('')}</pre>`;
}
function reviewPage() {
  const blocked=!state.validated||!state.checks||state.scenario==='stale'||state.applied;
  return `<div class="page">${pageHeading('Review change','One declaration · one file',button('Apply change','apply-change','check','primary',blocked?'disabled':'') )}${stepper(3)}${blocked?notice(state.applied?'This draft has already been applied.':state.scenario==='stale'?'Source changed. Refresh the draft before applying.':'Draft changed. Validate and run checks again.','',textLink(state.applied?'View receipt':'Open draft',state.applied?'receipt':'draft')):''}<div class="toolbar"><div class="row wrap"><code>${esc(state.editorFile)}</code><span class="accent small">+${draftDiff().added.length}</span><span class="small" style="color:var(--red)">−${draftDiff().removed.length}</span></div><div class="filters">${['Unified','Split'].map(mode=>`<button class="filter ${state.diffMode===mode?'active':''}" data-action="diff-mode" data-value="${mode}" aria-pressed="${state.diffMode===mode}">${mode}</button>`).join('')}</div></div><div class="code-block">${diffContent()}</div><div class="grid three-columns section-gap">${[['Draft',state.validated?'Validated':'Edited'],['Checks',state.checks?'3 passed':'Not current'],['Source',state.scenario==='stale'?'Changed':'Current']].map(([name,value])=>`<div class="panel panel-pad"><div class="row between"><span class="small muted">${name}</span>${badge(value,value==='Edited'||value==='Not current'||value==='Changed'?'amber':'green')}</div></div>`).join('')}</div><div class="form-footer section-gap">${link('Edit draft','draft','back','ghost')}<span class="small muted">${icon('lock')} Source changes only after Apply</span></div></div>`;
}
function receiptPage() { return `<div class="page">${stepper(4)}<section class="receipt"><div class="success-icon">${icon(state.undone?'undo':'check')}</div><h1>${state.undone?'Change undone.':'Change applied.'}</h1><p><code>${esc(state.editorFile)}</code></p><div class="panel detail-meta">${meta('Declaration',`<code>${esc(state.symbol)}</code>`)}${meta('Change',state.undone?'Original source restored':esc(state.changeLabel))}${meta('Checks','3 passed before Apply')}${meta('Receipt','chg_82f1c9 · today, 10:52')}</div>${state.scenario==='stale'?`<div class="section-gap">${notice('File changed since Apply. Undo is unavailable.','')}</div>`:''}<div class="actions">${link('Back to editor','editor','code','primary')}${!state.undone?button('Undo change','undo-change','undo','',state.scenario==='stale'?'disabled':''):''}</div></section></div>`; }

function benchmarkPage() {
  const hit=state.benchmarkName==='BenchmarkCacheHit';
  return `<div class="page">${pageHeading('Benchmark','Compare the source and draft in a copied workspace.',button(state.benchmarkDone?'Run again':'Run benchmark','run-benchmark','play','primary'))}<div class="panel panel-pad"><div class="row between wrap"><div><label class="field-label" for="benchmark-target" style="margin-top:0">Compatible benchmark</label><select class="field" id="benchmark-target"><option ${state.benchmarkName==='BenchmarkCacheHit'?'selected':''}>BenchmarkCacheHit</option><option ${state.benchmarkName==='BenchmarkCacheMiss'?'selected':''}>BenchmarkCacheMiss</option></select></div><div>${badge('internal/cache')} ${badge('Draft comparison','blue')}</div></div></div>${state.benchmarkDone?`<div class="grid three-columns section-gap"><section class="panel measure"><h3>Time / operation</h3><div class="big-number">${hit?230:55}<span class="number-unit">ns/op</span></div><p>Source: ${hit?890:52} ns/op</p></section><section class="panel measure"><h3>Allocations</h3><div class="big-number">0<span class="number-unit">allocs/op</span></div><p>Source: ${hit?1:0} allocs/op</p></section><section class="panel measure"><h3>Memory / operation</h3><div class="big-number">0<span class="number-unit">B/op</span></div><p>Source: ${hit?64:0} B/op</p></section></div><div class="section-gap">${panel('Time per operation',`<div class="bar-comparison" role="img" aria-label="Sample measurement: source ${hit?890:52} nanoseconds per operation; draft ${hit?230:55} nanoseconds per operation"><div class="bar-row"><span>Source</span><div class="track"><div class="bar" style="width:${hit?100:94.5}%"></div></div><span class="bar-value">${hit?890:52} ns/op</span></div><div class="bar-row"><span>Draft</span><div class="track"><div class="bar after" style="width:${hit?26:100}%"></div></div><span class="bar-value">${hit?230:55} ns/op</span></div></div><div class="form-footer"><span class="small muted">Illustrative measurements · 5 samples</span>${link('Review draft','review','arrow','small')}</div>`,badge('Measured sample','green'))}</div>`:`<div class="section-gap">${emptyState('Ready to measure','No benchmark results for this draft.','','gauge')}</div>`}</div>`;
}
function terminalView(docked=false) {
  const session=state.terminalTabs.find(tab=>tab.id===state.activeTerminal);
  return `<div class="terminal-page"><div class="terminal-toolbar"><span class="small muted">Terminal</span>${state.terminalTabs.map(tab=>`<div class="terminal-tab ${tab.id===state.activeTerminal?'active':''}"><button data-action="terminal-select" data-id="${tab.id}">${tab.name} ${tab.id}</button><button data-action="terminal-close" data-id="${tab.id}" aria-label="Close shell ${tab.id}">${icon('close')}</button></div>`).join('')}<button class="icon-button" data-action="terminal-new" aria-label="New shell">${icon('plus')}</button>${docked?'<button class="icon-button" data-action="toggle-terminal" aria-label="Hide terminal" style="margin-left:auto">'+icon('minus')+'</button>':`<span class="small muted" style="margin-left:auto">${esc(state.project)}</span>`}</div><div class="terminal-canvas">${!docked?'<div class="terminal-caption">Sample shell · commands only update this preview</div>':''}${session?`<pre class="terminal-output">${esc(session.lines.join('\n'))}</pre><form id="${docked?'dock':'page'}-terminal-form" class="terminal-input-row"><span class="accent">❯</span><label class="sr-only" for="${docked?'dock':'page'}-terminal-input">Sample terminal command</label><input id="${docked?'dock':'page'}-terminal-input" autocomplete="off" spellcheck="false" placeholder="Try pwd, ls, or help"></form>`:`<div class="empty"><h2>No open shells</h2>${button('New shell','terminal-new','plus')}</div>`}</div></div>`;
}
function modelsPage() {
  const local=state.modelScope==='Analyze';
  return `<div class="page">${pageHeading('Models','Configured destinations for each task.')}<div class="tabs">${['Analyze','Chat','Function'].map(scope=>`<button class="tab ${state.modelScope===scope?'active':''}" data-action="model-scope" data-value="${scope}">${scope}</button>`).join('')}</div><div class="grid two-columns"><section class="panel"><div class="settings-row"><span class="model-icon">${icon(local?'laptop':'cloud')}</span><div class="list-copy"><h2>${local?'Local model':'Cloud model'}</h2><p>${state.modelScope} scope</p></div>${badge(local?'Local':'Remote',local?'green':'blue')}</div><div class="detail-meta">${meta('Model',local?'qwen2.5-coder:14b':'Configured Function / Chat model')}${meta('Destination',local?'<code>http://localhost:11434</code>':'<code>https://provider.example.invalid</code>')}${meta('Provider status','Not checked')}${meta('Source sharing',local?'Stays on this machine':'Confirmation per request')}</div><details><summary>Configuration</summary><p>Managed in the daemon configuration.</p></details></section>${panel('Daemon',`<div class="settings-row"><span class="model-icon">${icon('activity')}</span><div class="list-copy"><h3>${state.scenario==='offline'?'Disconnected':'Connected'}</h3><p>localhost:9090</p></div>${badge(state.scenario==='offline'?'Offline':'Local',state.scenario==='offline'?'red':'green')}</div><div class="panel-body"><p class="small muted">Provider availability is checked separately.</p></div><div class="form-footer"><span class="small muted">Connection only</span>${button('Reconnect','reconnect','refresh','small')}</div>`)}</div></div>`;
}
function diagramsPage() { return `<div class="page">${pageHeading('Architecture & flows',esc(state.project),button('Copy source','copy-diagram','copy'))}<div class="toolbar"><div class="filters">${['Architecture','Request flow'].map(value=>`<button class="filter ${state.diagram===value?'active':''}" data-action="diagram-type" data-value="${value}">${value}</button>`).join('')}</div><div class="actions"><button class="icon-button" data-action="zoom-out" aria-label="Zoom out">${icon('minus')}</button><span class="small muted">${state.zoom}%</span><button class="icon-button" data-action="zoom-in" aria-label="Zoom in">${icon('plus')}</button>${button('Reset','zoom-reset','','small ghost')}</div></div><section class="panel"><div class="diagram-surface" style="min-height:420px"><div style="width:${state.zoom}%;min-width:${state.zoom*5}px">${diagramSvg()}</div></div><details><summary>Mermaid source</summary><pre id="diagram-source">${esc(mermaidSource())}</pre></details></section></div>`; }
function mermaidSource() { return state.diagram==='Architecture'?'flowchart LR\n  API[HTTP API] --> Service\n  Config --> Service\n  Service --> Cache\n  Service --> Storage':'flowchart LR\n  Request --> Router --> Cache --> Response'; }
function scanPage() { return `<div class="page">${pageHeading('Verified scan','Go parser, vet and tests.',button(state.scanDone?'Run again':'Run scan','run-scan','shield','primary'))}<div class="grid two-columns">${panel('Scan scope',`<div class="detail-meta">${meta('Project',esc(state.project))}${meta('Files','24 selected files')}${meta('Commands','Go parser · go vet ./... · go test ./...')}${meta('Workspace','Temporary project copy')}</div>`)}${panel('Results',state.scanDone?`<div class="check-row">${icon('circleCheck')}<div><h3>Parser</h3><p>Passed</p></div></div><div class="check-row">${icon('circleCheck')}<div><h3>Go vet</h3><p>No diagnostics</p></div></div><div class="check-row">${icon('warning')}<div><h3>Tests</h3><p>1 failed · TestStoreLoadExpired</p></div></div>`:`<div class="empty" style="min-height:230px">${icon('shield')}<h2>No scan results</h2><p>Run a scan to collect verified evidence.</p></div>`)}</div>${state.scanDone?`<div class="section-gap">${panel('Diagnostic',`<div class="panel-body"><h3>TestStoreLoadExpired</h3><p class="small" style="margin:10px 0">Expected a cache miss; got an expired value.</p><code>internal/cache/store_test.go:71</code><div class="actions section-gap">${link('Open source','editor','code')}${link('View related finding','bug-detail','bug')}</div></div>`,badge('Test failure','red'))}</div>`:''}</div>`; }
function manifestPage() { return `<div class="page">${pageHeading('Request context',`<code>${esc(state.editorFile)} / ${esc(state.symbol)}</code>`,link('Back to assistant','assistant','back','ghost'))}<div class="grid three-columns"><div class="panel panel-pad"><div class="small muted">Included</div><div class="metric-number">3<span class="number-unit">files</span></div></div><div class="panel panel-pad"><div class="small muted">Payload</div><div class="metric-number">2.4<span class="number-unit">KB</span></div></div><div class="panel panel-pad"><div class="small muted">Destination</div><h2 style="margin-top:22px">Cloud provider</h2>${badge('Confirmation required','blue')}</div></div><div class="section-gap">${panel('Included files',`<div class="table-wrap"><table><thead><tr><th>File</th><th>Scope</th><th>Size</th></tr></thead><tbody>${[[state.editorFile,'Selected declaration','1.1 KB'],['internal/cache/store_test.go','Related tests','0.9 KB'],['go.mod','Module context','0.4 KB']].map(([path,scope,size])=>`<tr><td class="path">${esc(path)}</td><td>${scope}</td><td class="mono small">${size}</td></tr>`).join('')}</tbody></table></div>`)}</div><div class="section-gap">${panel('Excluded',`<div class="list-row"><span class="list-copy"><strong>config.yaml</strong><small>Local configuration</small></span>${badge('Sensitive')}</div><div class="list-row"><span class="list-copy"><strong>vendor/ · build/</strong><small>Dependency and generated files</small></span>${badge('Ignored')}</div>`)}</div></div>`; }
function searchItems() { return [
  {label:'internal/cache/store.go',hint:'Source file · Go',kind:'Files',icon:'file',route:'editor'},
  {label:'internal/cache/store_test.go',hint:'Tests · Go',kind:'Files',icon:'file',route:'editor',path:'internal/cache/store_test.go'},
  {label:'internal/api/server.go',hint:'Source file · Go',kind:'Files',icon:'file',route:'editor',path:'internal/api/server.go'},
  {label:'Load',hint:'internal/cache/store.go:38',kind:'Symbols',icon:'code',route:'context'},
  {label:'Store',hint:'internal/cache/store.go:8',kind:'Symbols',icon:'code',route:'editor'},
  {label:'Start analysis',hint:'Review scope and destinations',kind:'Commands',icon:'play',route:'analysis-preview'},
  {label:'New declaration',hint:'Add a Go function or type',kind:'Commands',icon:'plus',route:'new-declaration'},
  {label:'Review draft',hint:'Inspect the proposed change',kind:'Commands',icon:'layers',route:'review'},
  {label:'Open terminal',hint:'Local shell',kind:'Commands',icon:'terminal',route:'terminal'},
  {label:'All screens',hint:'Explore the prototype',kind:'Commands',icon:'grid',route:'states'},
]; }
function searchRows() { const matches=searchItems().filter(item=>(state.searchScope==='All'||item.kind===state.searchScope)&&`${item.label} ${item.hint}`.toLowerCase().includes(state.searchQuery.toLowerCase()));return matches.map(item=>`<a class="search-result" href="#${item.route}" ${item.path?`data-source="${item.path}"`:''}>${icon(item.icon)}<span><strong>${item.label}</strong><small>${item.hint}</small></span><span class="search-key">${icon('arrow')}</span></a>`).join('') || '<div class="empty"><h2>No results</h2><p>Try a file, symbol, or command.</p></div>'; }
function searchPage() { return `<div class="page"><div class="search-page"><div class="panel"><div class="large-search"><div class="input-wrap">${icon('search')}<label class="sr-only" for="global-search">Search files, symbols, and commands</label><input id="global-search" placeholder="Files, symbols, commands…" value="${esc(state.searchQuery)}"></div></div><div class="filters" style="padding:12px 17px">${['All','Files','Symbols','Commands'].map(scope=>`<button class="filter ${scope===state.searchScope?'active':''}" data-action="search-scope" data-value="${scope}">${scope}</button>`).join('')}</div><div id="search-results">${searchRows()}</div><div class="form-footer"><span class="small muted">Tab to navigate · Enter to open</span>${link('Close','summary','','small ghost')}</div></div></div></div>`; }
function statesPage() {
  return `<div class="page">${pageHeading('Every screen','28 connected screens. Choose a page or a state.')}<div class="filters section-gap" style="margin-bottom:25px">${[['empty','Empty'],['loading','Loading'],['failed','Failed'],['partial','Partial'],['canceled','Canceled'],['stale','Outdated'],['offline','Offline']].map(([value,label])=>button(label,'show-state','','small',`data-value="${value}"`)).join('')}</div>${Object.entries(routeGroups).filter(([group])=>group!=='Prototype').map(([group,items])=>`<section class="section-gap"><div class="eyebrow">${group}</div><div class="screen-grid">${items.map(([id,title,,symbol])=>`<a class="panel screen-tile" href="#${id}"><span class="row between" style="width:100%">${icon(symbol)}<span class="muted">${icon('upRight')}</span></span><h2>${title}</h2></a>`).join('')}</div></section>`).join('')}</div>`;
}
const pageRenderers={summary:summaryPage,welcome:welcomePage,project:projectPage,analysis:analysisPage,'analysis-preview':previewPage,'analysis-run':runPage,bugs:()=>resultsPage('bugs'),'bug-detail':()=>detailPage('bugs'),performance:()=>resultsPage('performance'),'performance-detail':()=>detailPage('performance'),security:()=>resultsPage('security'),'security-detail':()=>detailPage('security'),editor:editorPage,context:contextPage,assistant:assistantPage,'new-declaration':newDeclarationPage,draft:draftPage,checks:checksPage,review:reviewPage,receipt:receiptPage,benchmark:benchmarkPage,terminal:()=>terminalView(),search:searchPage,models:modelsPage,diagrams:diagramsPage,scan:scanPage,manifest:manifestPage,states:statesPage};

function scenarioContent() {
  if(route==='states'||route==='welcome') return '';
  const s=state.scenario;
  if(s==='offline') return notice('Daemon disconnected. Saved results are available.','error',button('Reconnect','reconnect','refresh','small'));
  if(s==='failed'&&route!=='analysis-run') return notice('Could not load the latest results. Showing saved data.','error',button('Retry','retry','refresh','small'));
  if(s==='stale'&&!['review','receipt'].includes(route)) return notice('Source changed since this analysis.','',link('Review new analysis','analysis-preview','refresh','small'));
  if(s==='partial'&&route!=='analysis-run') return notice('Analysis incomplete. Available results are shown.','',link('View run','analysis-run','arrow','small'));
  if(s==='canceled'&&route!=='analysis-run') return notice('Analysis canceled. Completed results retained.','',link('New analysis','analysis-preview','play','small'));
  return '';
}
function render() {
  const info=routes.find(([id])=>id===route)||routes[0];
  document.title=`Mini-Orca · ${info[1]} · Mockup`;
  document.getElementById('scene').value=route;
  document.getElementById('scenario').value=state.scenario;
  document.getElementById('finish-run').hidden=route!=='analysis-run'||state.runStatus!=='Running'||state.scenario!=='ready';
  document.getElementById('project-name').textContent=state.project;
  document.querySelector('.project-avatar').textContent=state.project[0].toUpperCase();
  document.getElementById('footer-file').textContent=`${state.project} / Go workspace`;
  document.getElementById('breadcrumbs').innerHTML=`<a href="#summary" class="muted">${esc(state.project)}</a><span class="slash">/</span><span>${info[1]}</span>`;
  document.getElementById('connection').innerHTML=`<span class="status-dot ${state.scenario==='offline'?'offline':''}"></span>Daemon ${state.scenario==='offline'?'offline':'connected'}`;
  const active=info[2]==='Editor'?'editor':route.startsWith('analysis')?'analysis':route.startsWith('bug')?'bugs':route.startsWith('performance')?'performance':route.startsWith('security')?'security':route;
  const navItems=[['summary','Summary','grid',''],['analysis','Analysis','activity',''],['bugs','Bugs','bug','3'],['performance','Performance','gauge','2'],['security','Security','shield','1'],['editor','Editor','code','']];
  const nav=items=>items.map(([id,label,symbol,count])=>`<a class="nav-link" href="#${id}" aria-label="${label}" title="${label}" ${active===id?'aria-current="page"':''}>${icon(symbol)}<span>${label}</span>${count?`<small class="nav-count">${count}</small>`:''}</a>`).join('');
  document.getElementById('navigation').innerHTML='<div class="nav-label">Workspace</div>'+nav(navItems.slice(0,5))+'<div class="nav-rule"></div>'+nav(navItems.slice(5));
  document.getElementById('utility-navigation').innerHTML=nav([['terminal','Terminal','terminal',''],['models','Models','sparkles',''],['project','Project','folder','']]);
  if(state.scenario==='empty'&&!['states','welcome','models','project'].includes(route)) {
    main.innerHTML=`<div class="page">${pageHeading(info[1])}${emptyState('No results yet','Select files and start your first analysis.',button('Choose files','choose-files','plus','primary'))}</div>`;
  } else if(state.scenario==='loading'&&route!=='states') {
    main.innerHTML=`<div class="page" aria-busy="true">${pageHeading(info[1],'Loading saved data…') }<div class="grid three-columns">${Array.from({length:3},()=>'<div class="panel skeleton-panel"><div class="skeleton short"></div><div class="skeleton medium"></div><div class="skeleton"></div></div>').join('')}</div><div class="panel skeleton-panel section-gap"><div class="skeleton short"></div><div class="skeleton"></div><div class="skeleton medium"></div></div></div>`;
  } else {
    main.innerHTML=(pageRenderers[route]||summaryPage)();
    const feedback=scenarioContent();
    if(feedback){const target=main.querySelector('.page'); if(target)target.insertAdjacentHTML('afterbegin',feedback);else main.insertAdjacentHTML('afterbegin',feedback);}
  }
  renderDock();
  document.querySelectorAll('[data-icon]').forEach(el=>{el.innerHTML=icon(el.dataset.icon);});
  document.getElementById('theme-toggle').innerHTML=icon(document.documentElement.dataset.theme==='dark'?'sun':'moon');
}
function renderDock(){document.getElementById('terminal-dock').innerHTML=state.terminalOpen&&route!=='terminal'?terminalView(true):'';}
function navigate(target) { if(location.hash.slice(1)===target){route=target;render();main.scrollTop=0;main.focus({preventScroll:true});}else location.hash=target; }
function toast(message){const el=document.getElementById('toast');el.textContent=message;el.hidden=false;clearTimeout(state.toastTimer);state.toastTimer=setTimeout(()=>{el.hidden=true;},3300);}
function closeDialog(){dialog.close();confirmAction=null;if(lastFocus?.isConnected)lastFocus.focus();}
function showDialog(title,body,confirmLabel,action,{danger=false,gate=false}={}) {
  lastFocus=document.activeElement;confirmAction=action;confirmGate=gate;
  dialog.innerHTML=`<div class="dialog-head"><h2 id="dialog-title">${title}</h2><button class="icon-button" data-action="dialog-close" aria-label="Close dialog">${icon('close')}</button></div><div class="dialog-body">${body}</div><div class="dialog-actions">${button('Cancel','dialog-close','','ghost')}${button(confirmLabel,'dialog-confirm','',danger?'danger':'primary',gate?'disabled':'')}</div>`;
  if(!dialog.open)dialog.showModal();
}
function confirmCloud(onConfirmed){showDialog('Send source to cloud?',`<p>The configured Function provider will receive this declaration and related context.</p><div class="panel detail-meta">${meta('Target',`<code>${esc(state.editorFile)} / ${esc(state.symbol)}</code>`)}${meta('Context','3 files · 2.4 KB')}${meta('Destination','provider.example.invalid')}</div><label class="checkbox-line"><input type="checkbox" id="dialog-consent">Allow this request.</label>`,'Send request',onConfirmed,{gate:true});}
function confirmExecution(kind,commands,onConfirmed){showDialog(`Run ${kind}?`,`<p>These commands will run in a temporary copy of <strong>${esc(state.project)}</strong>.</p><div class="code-block" style="margin-top:16px"><pre>${esc(commands)}</pre></div><label class="checkbox-line"><input type="checkbox" id="dialog-consent">Trust this project for this execution.</label>`,`Run ${kind}`,onConfirmed,{gate:true});}

function openProjectDialog() {
  showDialog('Open project',`<label class="field-label" for="project-path" style="margin-top:0">Project folder</label><input id="project-path" value="~/Developer/${esc(state.project)}" autocomplete="off"><div class="eyebrow" style="margin-top:23px">RECENT</div>${['harbor','atlas'].map(name=>`<button class="dialog-project" data-action="choose-project" data-project="${name}"><span class="project-avatar">${name[0].toUpperCase()}</span><span class="list-copy"><strong>${name}</strong><small>~/Developer/${name}</small></span>${icon('chevron')}</button>`).join('')}`,'Continue',()=>{
    const path=document.getElementById('project-path').value.trim();
    if(!path){toast('Enter a project folder.');openProjectDialog();return;}
    reviewProjectSwitch(path.split('/').filter(Boolean).at(-1));
  });
}
function reviewProjectSwitch(name) {
  showDialog(`Open ${esc(name)}?`,`<p>${state.draftDirty?'The current draft will be discarded. ':''}${state.terminalTabs.length?'Open shells will be closed.':''}</p><div class="panel detail-meta">${meta('Project',esc(name))}${meta('Analyze destination','Local model · localhost:11434')}</div>`,'Open project',()=>{state.project=name;state.draftDirty=false;state.terminalTabs=[];state.terminalOpen=false;state.scenario='ready';navigate('summary');toast(`Opened ${name} in the preview.`);});
}
function currentCategory(){return route.startsWith('security')?'security':route.startsWith('performance')?'performance':'bugs';}
function chooseSource(path) {
  const apply=()=>{state.editorFile=path;state.draftDirty=false;state.symbol=path.includes('local.go')?'ReadFile':path.includes('server.go')?'Serve':'Load';navigate('editor');};
  if(state.draftDirty&&path!==state.editorFile)showDialog('Discard current draft?',`<p>Open <code>${esc(path)}</code> and discard the edited draft?</p>`,'Discard draft',apply,{danger:true});else apply();
}
function preparedDraft() {state.validated=false;state.checks=false;state.applied=false;state.undone=false;state.draftDirty=false;state.scenario='ready';navigate('draft');}
function terminalCommand(form){
  const input=form.querySelector('input'),command=input.value.trim();
  if(!command)return;
  const session=state.terminalTabs.find(tab=>tab.id===state.activeTerminal);if(!session)return;
  const output=command==='pwd'?`/Users/demo/Developer/${state.project}`:command==='ls'?'cmd/  docs/  internal/  go.mod  go.sum  README.md':command==='help'?'Preview commands: pwd, ls, git status, go test, clear. No shell process is running.':command.startsWith('git status')?'On branch main\nChanges not staged for commit:\n  modified: internal/cache/store.go':command.startsWith('go test')?'Sample output:\nok  example.com/harbor/internal/cache  0.008s':`Preview only: ${command}`;
  if(command==='clear')session.lines=[];else session.lines.push('❯ '+command,output,'');
  if(route==='terminal')main.innerHTML=terminalView();else renderDock();
  const next=document.getElementById(route==='terminal'?'page-terminal-input':'dock-terminal-input');next?.focus();
}
const actions={
  'open-project':openProjectDialog,
  'choose-project':el=>{if(dialog.open)closeDialog();reviewProjectSwitch(el.dataset.project);},
  'close-project':()=>showDialog('Close project?',`<p>${state.draftDirty?'Discard the current draft and close all shells?':'Open shells will be closed.'}</p>`,'Close project',()=>{state.terminalTabs=[];state.terminalOpen=false;state.draftDirty=false;navigate('welcome');}),
  reindex:()=>{state.scenario='ready';state.validated=false;state.checks=false;render();toast('Sample inventory refreshed. Draft needs revalidation.');},
  exclusions:()=>showDialog('Excluded files','<p><code>go.sum</code> is excluded from analysis.</p><div class="panel detail-meta">'+meta('Automatically ignored','vendor/ · build/ · config.yaml')+'</div>','Manage files',()=>navigate('analysis')),
  search:()=>navigate('search'),
  'toggle-terminal':()=>{if(route==='terminal'){navigate('summary');state.terminalOpen=false;}else{state.terminalOpen=!state.terminalOpen;renderDock();}},
  'choose-files':()=>{state.scenario='ready';navigate('analysis');},
  'file-filter':el=>{state.fileFilter=el.dataset.value;render();},
  'select-all':()=>{if(analysisLocked())return;state.selectedFiles=new Set(files.map(f=>f[0]));render();},
  'select-none':()=>{if(analysisLocked())return;state.selectedFiles.clear();render();},
  'start-analysis':()=>{if(!state.remoteConsent||!state.securityConsent||!state.selectedFiles.size)return;const resumed=state.runStatus==='Paused';state.runStatus='Running';if(!resumed)state.runTotal=state.selectedFiles.size;state.runCount=resumed?state.runCount:Math.min(12,Math.max(0,state.runTotal-1));state.remoteConsent=false;state.securityConsent=false;state.scenario='ready';navigate('analysis-run');},
  'pause-run':()=>{state.runStatus='Paused';render();},
  'cancel-run':()=>showDialog('Cancel analysis?','<p>Completed results will remain available.</p>','Cancel analysis',()=>{state.runStatus='Canceled';render();},{danger:true}),
  'complete-run':()=>{state.runStatus='Completed';state.runCount=state.runTotal;render();},
  'finding-filter':el=>{state.findingFilter=el.dataset.value;render();},
  'clear-findings':()=>{state.findingFilter='All';state.findingQuery='';render();},
  'finding-source':()=>{const f=findings[currentCategory()][state.selectedFinding[currentCategory()]];state.symbol=f.symbol;chooseSource(f.path);},
  'prepare-finding':()=>{const f=findings[currentCategory()][state.selectedFinding[currentCategory()]],fixture=changeFixtures[f.symbol]||changeFixtures.Load;const prepare=()=>{state.editorFile=f.path;state.symbol=f.symbol;state.request=f.title;state.draft=fixture.after;state.originalDeclaration=fixture.before;state.changeLabel=fixture.label;state.imports=fixture.imports;state.draftDirty=false;navigate('assistant');};if(state.draftDirty)showDialog('Discard current draft?','<p>Start a change for this finding?</p>','Discard draft',prepare,{danger:true});else prepare();},
  'source-file':el=>chooseSource(el.dataset.path),
  'select-symbol':el=>{const change=()=>{state.symbol=el.dataset.value;state.draftDirty=false;render();};if(state.draftDirty&&el.dataset.value!==state.symbol)showDialog('Discard current draft?','<p>Switching declarations will discard this draft.</p>','Discard draft',change,{danger:true});else change();},
  explain:()=>confirmCloud(()=>{state.explanation=true;render();}),
  'prompt-expiry':()=>{state.request='Handle expired cache entries without changing the method signature.';document.getElementById('request').value=state.request;document.getElementById('request').focus();},
  'prompt-simplify':()=>{state.request='Simplify this declaration while preserving its behavior.';document.getElementById('request').value=state.request;document.getElementById('request').focus();},
  'prepare-draft':()=>{state.request=document.getElementById('request').value.trim();if(!state.request){toast('Describe the change first.');return;}confirmCloud(preparedDraft);},
  'declaration-kind':el=>{state.declarationKind=el.dataset.value;render();},
  'prepare-new':()=>{const name=document.getElementById('declaration-name').value.trim(),request=document.getElementById('new-request').value.trim();state.declarationName=name;const error=document.getElementById('name-error');if(!/^[A-Za-z_][A-Za-z0-9_]*$/.test(name)||['func','type','var','package','import','return','map','interface'].includes(name)){error.textContent='Enter a valid Go declaration name.';return;}if(!request){error.textContent='Describe the declaration first.';return;}confirmCloud(()=>{state.symbol=name;state.request=request;state.originalDeclaration='';state.changeLabel='Add '+name;state.imports=state.declarationKind==='Type'?'':'time';state.draft=state.declarationKind==='Type'?`type ${name} struct {\n    Hits   uint64\n    Misses uint64\n}`:`func (s *Store) ${name}() {\n    s.mu.Lock()\n    defer s.mu.Unlock()\n\n    now := time.Now()\n    for key, entry := range s.entries {\n        if now.After(entry.ExpiresAt) {\n            delete(s.entries, key)\n        }\n    }\n}`;preparedDraft();});},
  'discard-draft':()=>showDialog('Discard draft?','<p>Your source file is unchanged.</p>','Discard draft',()=>{state.draft=defaultDraft;state.draftDirty=false;state.validated=false;state.checks=false;navigate('editor');},{danger:true}),
  'validate-draft':()=>{if(!state.draft.trim()){document.getElementById('draft-error').innerHTML=notice('The declaration cannot be empty.','error');return;}state.validated=true;state.checks=false;render();toast('Sample validation passed.');},
  'run-checks':()=>{if(!state.validated)return;confirmExecution('checks','gofmt (draft)\ngo test ./internal/cache -run TestStoreLoad\ngo vet ./internal/cache',()=>{state.checks=true;render();toast('All 3 sample checks passed.');});},
  'diff-mode':el=>{state.diffMode=el.dataset.value;render();},
  'apply-change':()=>{if(!state.validated||!state.checks||state.scenario==='stale'||state.applied)return;showDialog('Apply this change?',`<p>Replace <code>${esc(state.symbol)}</code> in <code>${esc(state.editorFile)}</code>.</p><div class="panel detail-meta">${meta('Scope','One declaration · one file')}${meta('Evidence','Validated · 3 checks passed')}${meta('Source','Current')}</div>`,'Apply change',()=>{state.appliedBefore=selectedSource();state.sourceVersions[state.editorFile]=state.originalDeclaration&&state.appliedBefore.includes(state.originalDeclaration)?state.appliedBefore.replace(state.originalDeclaration,state.draft):state.appliedBefore+'\n\n'+state.draft;state.applied=true;state.undone=false;state.draftDirty=false;navigate('receipt');});},
  'undo-change':()=>{if(state.scenario==='stale')return;showDialog('Undo this change?',`<p>Restore the previous version of <code>${esc(state.editorFile)}</code>.</p>`,'Undo change',()=>{if(state.appliedBefore)state.sourceVersions[state.editorFile]=state.appliedBefore;state.undone=true;state.applied=false;render();});},
  'run-benchmark':()=>confirmExecution('benchmark',`go test ./internal/cache -run ^$ -bench ${state.benchmarkName} -benchmem -count 5`,()=>{state.benchmarkDone=true;render();}),
  'run-scan':()=>confirmExecution('scan','go vet ./...\ngo test ./...',()=>{state.scanDone=true;render();}),
  'model-scope':el=>{state.modelScope=el.dataset.value;render();},
  reconnect:()=>{state.scenario='ready';render();toast('Sample daemon connection restored.');},
  retry:()=>{state.scenario='ready';render();},
  'search-scope':el=>{state.searchScope=el.dataset.value;render();document.getElementById('global-search')?.focus();},
  'terminal-new':()=>{state.terminalSequence++;state.activeTerminal=state.terminalSequence;state.terminalTabs.push({id:state.activeTerminal,name:'zsh',lines:[`${state.project} on main`,'']});if(route==='terminal')render();else renderDock();},
  'terminal-select':el=>{state.activeTerminal=Number(el.dataset.id);if(route==='terminal')render();else renderDock();},
  'terminal-close':el=>showDialog('Close shell?','<p>The shell and its child processes will close.</p>','Close shell',()=>{state.terminalTabs=state.terminalTabs.filter(tab=>tab.id!==Number(el.dataset.id));if(!state.terminalTabs.some(tab=>tab.id===state.activeTerminal))state.activeTerminal=state.terminalTabs[0]?.id??0;if(route==='terminal')render();else renderDock();}),
  'diagram-type':el=>{state.diagram=el.dataset.value;render();},
  'zoom-in':()=>{state.zoom=Math.min(200,state.zoom+25);render();},
  'zoom-out':()=>{state.zoom=Math.max(75,state.zoom-25);render();},
  'zoom-reset':()=>{state.zoom=100;render();},
  'copy-diagram':async()=>{try{await navigator.clipboard.writeText(mermaidSource());toast('Mermaid source copied.');}catch{showDialog('Diagram source',`<pre>${esc(mermaidSource())}</pre>`,'Done',()=>{});}},
  'show-state':el=>{state.scenario=el.dataset.value;navigate(['canceled','partial'].includes(state.scenario)?'analysis-run':state.scenario==='stale'?'review':'summary');},
  'dialog-close':closeDialog,
  'dialog-confirm':()=>{if(confirmGate&&!document.getElementById('dialog-consent')?.checked)return;const action=confirmAction;closeDialog();action?.();},
};
document.addEventListener('click',event=>{
  const control=event.target.closest('[data-action]');
  if(control&&!control.disabled){event.preventDefault();actions[control.dataset.action]?.(control);return;}
  const finding=event.target.closest('[data-finding]');
  if(finding){const [category,index]=finding.dataset.finding.split(':');state.selectedFinding[category]=Number(index);state.findingFilter='All';state.findingQuery='';}
  const source=event.target.closest('[data-source]');
  if(source){event.preventDefault();chooseSource(source.dataset.source);return;}
  const target=event.target.closest('a[href^="#"]');
  if(target?.getAttribute('href')===location.hash && target.getAttribute('href')!=='#main'){event.preventDefault();render();main.scrollTop=0;}
});
document.addEventListener('input',event=>{
  const el=event.target;
  if(el.id==='file-search'){state.fileQuery=el.value;document.getElementById('file-rows').innerHTML=fileRows();}
  if(el.id==='finding-search'){state.findingQuery=el.value;document.getElementById('finding-rows').innerHTML=resultRows(currentCategory());}
  if(el.id==='global-search'){state.searchQuery=el.value;document.getElementById('search-results').innerHTML=searchRows();}
  if(el.id==='request')state.request=el.value;
  if(el.id==='declaration-name')state.declarationName=el.value;
  if(el.id==='new-request')state.newRequest=el.value;
  if(el.id==='draft-code'||el.id==='imports'){state[el.id==='draft-code'?'draft':'imports']=el.value;state.validated=false;state.checks=false;state.benchmarkDone=false;state.draftDirty=true;document.getElementById('draft-badge').innerHTML=badge('Edited','amber');}
});
document.addEventListener('change',event=>{
  const el=event.target;
  if(el.id==='benchmark-target'){state.benchmarkName=el.value;state.benchmarkDone=false;render();}
  if(el.dataset.file){if(el.checked)state.selectedFiles.add(el.dataset.file);else state.selectedFiles.delete(el.dataset.file);document.getElementById('selected-count').textContent=state.selectedFiles.size;const path=el.dataset.file;document.getElementById('file-rows').innerHTML=fileRows();[...document.querySelectorAll('[data-file]')].find(input=>input.dataset.file===path)?.focus();}
  if(el.id==='analysis-remote'||el.id==='analysis-security'){state.remoteConsent=document.getElementById('analysis-remote').checked;state.securityConsent=document.getElementById('analysis-security').checked;document.querySelector('[data-action="start-analysis"]').disabled=!state.remoteConsent||!state.securityConsent||!state.selectedFiles.size;}
  if(el.id==='dialog-consent')dialog.querySelector('[data-action="dialog-confirm"]').disabled=!el.checked;
});
document.addEventListener('submit',event=>{if(event.target.id.endsWith('-terminal-form')){event.preventDefault();terminalCommand(event.target);}});
document.addEventListener('keydown',event=>{
  if(dialog.open)return;
  if((event.metaKey||event.ctrlKey)&&['k','p','j','o'].includes(event.key.toLowerCase())){event.preventDefault();const key=event.key.toLowerCase();if(key==='o')openProjectDialog();else if(key==='j')actions['toggle-terminal']();else{navigate('search');setTimeout(()=>document.getElementById('global-search')?.focus(),0);}}
});
dialog.addEventListener('cancel',()=>{confirmAction=null;});
document.getElementById('scene').innerHTML=Object.entries(routeGroups).map(([group,items])=>`<optgroup label="${group}">${items.map(([id,label])=>`<option value="${id}">${label}</option>`).join('')}</optgroup>`).join('');
document.getElementById('scene').addEventListener('change',event=>{state.scenario='ready';navigate(event.target.value);});
document.getElementById('scenario').addEventListener('change',event=>{state.scenario=event.target.value;render();});
document.getElementById('theme-toggle').addEventListener('click',()=>{const dark=document.documentElement.dataset.theme==='dark';document.documentElement.dataset.theme=dark?'light':'dark';document.getElementById('theme-toggle').setAttribute('aria-label',`Switch to ${dark?'dark':'light'} appearance`);document.getElementById('theme-toggle').innerHTML=icon(dark?'moon':'sun');});
document.getElementById('size-toggle').addEventListener('click',event=>{const large=document.documentElement.classList.toggle('large-text');event.currentTarget.setAttribute('aria-pressed',String(large));});
document.getElementById('reset-demo').addEventListener('click',()=>{clearTimeout(state.toastTimer);state=initialState();document.getElementById('toast').hidden=true;if(dialog.open)closeDialog();navigate('summary');});
window.addEventListener('hashchange',()=>{const next=location.hash.slice(1).split('?')[0];route=pageRenderers[next]?next:'summary';state.findingFilter='All';state.findingQuery='';render();main.scrollTop=0;main.focus({preventScroll:true});if(route==='search')document.getElementById('global-search')?.focus();});
route=pageRenderers[location.hash.slice(1)]?location.hash.slice(1):'summary';
render();
