// Package state provides persistence and retrieval of orchestrator state.
package state

import "time"

// Phase represents a phase in the orchestrator flow.
type Phase string

const (
	PhasePlanning       Phase = "planning"
	PhasePlanningReview Phase = "planning_review"
	PhaseCoding         Phase = "coding"
	PhaseTesting        Phase = "testing"
	PhaseReview         Phase = "review"
	PhaseHumanReview    Phase = "human_review"
)

// SessionStatus represents the current status of a session.
type SessionStatus string

const (
	SessionStatusPending   SessionStatus = "pending"
	SessionStatusRunning   SessionStatus = "running"
	SessionStatusPaused    SessionStatus = "paused"
	SessionStatusCompleted SessionStatus = "completed"
	SessionStatusFailed    SessionStatus = "failed"
	SessionStatusCancelled SessionStatus = "cancelled"
)

// PlanStatus represents the status of a plan.
type PlanStatus string

const (
	PlanStatusDraft      PlanStatus = "draft"
	PlanStatusApproved   PlanStatus = "approved"
	PlanStatusRejected   PlanStatus = "rejected"
	PlanStatusInProgress PlanStatus = "in_progress"
	PlanStatusCompleted  PlanStatus = "completed"
)

// UnitStatus represents the status of a plan unit.
type UnitStatus string

const (
	UnitStatusPending   UnitStatus = "pending"
	UnitStatusCoding    UnitStatus = "coding"
	UnitStatusTesting   UnitStatus = "testing"
	UnitStatusReview    UnitStatus = "review"
	UnitStatusCompleted UnitStatus = "completed"
	UnitStatusFailed    UnitStatus = "failed"
)

// TestDefinition represents a test definition for a plan unit.
type TestDefinition struct {
	// Name is the name of the test.
	Name string
	// Description is a description of what the test validates.
	Description string
	// Code is the test code.
	Code string
}

// ReviewComment represents a review comment on a plan unit.
type ReviewComment struct {
	// Author is the name of the reviewer.
	Author string
	// Line is the line number the comment refers to (0 if not line-specific).
	Line int
	// Content is the comment text.
	Content string
	// Resolved indicates whether the comment has been addressed.
	Resolved bool
}

// PlanUnit represents an atomic unit of work within a plan.
type PlanUnit struct {
	// ID is the unique identifier for the unit.
	ID string
	// Name is the name of the unit.
	Name string
	// Description is a detailed description of what needs to be done.
	Description string
	// Dependencies are references to other unit IDs that must complete first.
	Dependencies []string
	// File is the target file for this unit.
	File string
	// UnitType is the type of the unit (function, struct, class).
	UnitType string
	// GeneratedCode is the code generated for this unit.
	GeneratedCode string
	// Status is the current status of the unit.
	Status UnitStatus
	// Tests are the test definitions for this unit.
	Tests []TestDefinition
	// ReviewComments are the review comments on this unit.
	ReviewComments []ReviewComment
	// RetryCount is the number of times this unit has been retried.
	RetryCount int
}

// Plan represents an execution plan generated by the planner agent.
type Plan struct {
	// ID is the unique identifier for the plan.
	ID string
	// SessionID is the ID of the session this plan belongs to.
	SessionID string
	// GeneratedAt is when the plan was generated.
	GeneratedAt time.Time
	// GeneratedBy is the name of the agent that generated the plan.
	GeneratedBy string
	// Units are the atomic units of work in this plan.
	Units []PlanUnit
	// Status is the current status of the plan.
	Status PlanStatus
	// ApprovedAt is when the plan was approved.
	ApprovedAt time.Time
	// ApprovedBy is the name of the approver.
	ApprovedBy string
	// RejectionReason is the reason for plan rejection.
	RejectionReason string
}

// AtomicUnit represents a single unit of work within a plan.
type AtomicUnit struct {
	// ID is the unique identifier for the atomic unit.
	ID string
	// Title is the title of the atomic unit.
	Title string
	// Description is a brief description of the atomic unit.
	Description string
	// Phase is the phase in which this unit should be executed.
	Phase Phase
	// Dependencies are the IDs of atomic units that must complete before this one.
	Dependencies []string
	// Status is the current status of the atomic unit.
	Status string
}

// PhaseStatus represents the status of a phase execution.
type PhaseStatus string

const (
	PhaseStatusPending    PhaseStatus = "pending"
	PhaseStatusInProgress PhaseStatus = "in_progress"
	PhaseStatusCompleted  PhaseStatus = "completed"
	PhaseStatusFailed     PhaseStatus = "failed"
	PhaseStatusSkipped    PhaseStatus = "skipped"
)

// PhaseHistory records the history of a single phase execution.
type PhaseHistory struct {
	// ID is the unique identifier for the phase history entry.
	ID string
	// SessionID is the ID of the session this phase belongs to.
	SessionID string
	// Phase is the phase that was executed.
	Phase string
	// StartedAt is when the phase execution started.
	StartedAt time.Time
	// CompletedAt is when the phase execution completed.
	CompletedAt time.Time
	// Status is the result status of the phase execution.
	Status PhaseStatus
	// Output contains the output of the phase execution.
	Output string
	// Error contains any error that occurred during the phase execution.
	Error string
	// RetryCount is the number of times this phase was retried.
	RetryCount int
}

// Session represents a single execution session within the pipeline.
type Session struct {
	// ID is the unique identifier for the session (UUID).
	ID string
	// Goal is the high-level goal of the session.
	Goal string
	// ProjectPath is the path to the project directory.
	ProjectPath string
	// ProjectType is the type of the project (e.g., "go", "python").
	ProjectType string
	// CreatedAt is when the session was created.
	CreatedAt time.Time
	// UpdatedAt is when the session was last updated.
	UpdatedAt time.Time
	// CurrentPhase is the current phase of the session.
	CurrentPhase Phase
	// Status is the current status of the session.
	Status SessionStatus
	// Plan is the execution plan for the session.
	Plan *Plan
	// AtomicUnits are the atomic units of work for this session.
	AtomicUnits []AtomicUnit
	// History contains the execution history of each phase.
	History []PhaseHistory
	// Error contains any error that occurred during the session.
	Error string
}
