package project

const (
	instructionProject  = "Project overview and architecture"
	instructionBuild    = "Build and development"
	instructionCode     = "Code style and conventions"
	instructionTests    = "Testing and validation"
	instructionSecurity = "Security and data"
	instructionUI       = "UI and accessibility"
	instructionDocs     = "Documentation"
	instructionWorkflow = "Review and handoff"
)

type instructionRule struct {
	signal string
	preset InstructionPreset
}

// Categories follow common AGENTS.md sections, not a required Markdown schema.
// Each choice is independent so users can select only rules they want to adopt.
func projectInstructionRules() []instructionRule {
	return []instructionRule{
		{"Go", InstructionPreset{ID: "go", Category: instructionCode, Label: "Follow Go conventions", Content: "Format changed Go code with gofmt. Preserve wrapped errors and context cancellation; use deterministic tests for changed behavior and error paths. Run the project's documented Go checks and report their results."}},
		{"Go", InstructionPreset{ID: "go-packages", Category: instructionProject, Label: "Keep Go package ownership clear", Content: "Trace the entry point, owning package and callers before changing Go behavior. Keep transport, business rules and persistence in their existing packages; introduce interfaces at real consumer boundaries rather than for hypothetical reuse."}},
		{"Go", InstructionPreset{ID: "go-errors", Category: instructionCode, Label: "Preserve Go error contracts", Content: "Return errors with useful operation context and preserve errors.Is/errors.As behavior when wrapping. Handle cleanup failures deliberately. Do not replace a failed operation with a zero value or log the same error at every layer."}},
		{"Go", InstructionPreset{ID: "go-concurrency", Category: instructionCode, Label: "Own goroutines and cancellation", Content: "Give each goroutine an owner and a bounded lifetime. Pass context through blocking operations, avoid holding locks during network or subprocess work, and use deterministic synchronization in tests for cancellation and concurrent state changes."}},
		{"Go", InstructionPreset{ID: "go-tests", Category: instructionTests, Label: "Test Go packages and race-sensitive paths", Content: "Exercise exported behavior with temporary directories and fake dependencies. Cover wrapped errors, cancellation and boundary inputs. Run focused package tests, then the owning module's documented tests and vet; use race detection for changes to shared state or background work."}},

		{"JavaScript", InstructionPreset{ID: "javascript", Category: instructionCode, Label: "Preserve JavaScript and TypeScript contracts", Content: "Preserve public types and API contracts. Handle rejected promises and stale asynchronous results explicitly. Use the project's existing formatter, type checks and test commands."}},
		{"JavaScript", InstructionPreset{ID: "javascript-tooling", Category: instructionBuild, Label: "Use the existing Node package workflow", Content: "Use the package manager, runtime version and package scripts already configured for the owning package. Keep its lockfile consistent when dependencies change; do not mix package managers, invent script names or upgrade the toolchain as part of an unrelated feature."}},
		{"JavaScript", InstructionPreset{ID: "javascript-async", Category: instructionCode, Label: "Handle asynchronous state explicitly", Content: "Handle promise rejection and cancellation at the operation owner. Reject late results after navigation or replacement requests, clean up subscriptions and timers, and distinguish loading, empty, failed and successful states."}},
		{"TypeScript", InstructionPreset{ID: "typescript-types", Category: instructionCode, Label: "Keep TypeScript boundaries typed", Content: "Validate external data before treating it as a domain type. Model distinct states with explicit types, preserve optional versus nullable fields, and avoid broad any casts or non-null assertions that hide missing validation."}},
		{"JavaScript", InstructionPreset{ID: "javascript-tests", Category: instructionTests, Label: "Test observable web and Node behavior", Content: "Use the existing test runner to exercise public behavior, rejected promises and invalid input. Keep timers, network calls and time-dependent values deterministic; run the package's configured type, lint and build checks without weakening their settings."}},

		{"UI", InstructionPreset{ID: "ui", Category: instructionUI, Label: "Keep interfaces accessible", Content: "Keep controls labeled and keyboard accessible, with visible focus and clear loading, empty and error states. Verify changed layouts at narrow widths and larger text sizes."}},
		{"UI", InstructionPreset{ID: "ui-forms", Category: instructionUI, Label: "Make forms and recovery understandable", Content: "Associate labels and validation messages with their controls. Preserve user input after recoverable failures, show pending submission state, prevent accidental duplicate actions and provide a clear retry or cancel path."}},
		{"UI", InstructionPreset{ID: "ui-layout", Category: instructionUI, Label: "Support responsive layouts and long content", Content: "Verify narrow and wide layouts, larger text, long labels and long paths. Keep primary actions reachable and content selectable, use the existing design system, and supplement color indicators with text or accessible state."}},
		{"UI", InstructionPreset{ID: "ui-tests", Category: instructionTests, Label: "Verify user interactions and UI states", Content: "Test keyboard activation, focus behavior, validation and recovery through production components. Cover loading, empty, failed and disabled states as well as success. Use rendered layout checks for clipping and contrast; report what automated checks cannot establish."}},
		{"React", InstructionPreset{ID: "react-state", Category: instructionProject, Label: "Keep React state with its owner", Content: "Keep render functions pure and store state in the component or workflow that owns it. Derive display values from existing state instead of maintaining duplicate state, and update collections immutably so renders reflect the current operation."}},
		{"React", InstructionPreset{ID: "react-effects", Category: instructionCode, Label: "Bound React effects and subscriptions", Content: "Declare effect dependencies accurately and clean up subscriptions, timers and requests. Start user-requested work from explicit actions; guard asynchronous results against stale identities instead of relying only on an unmount flag."}},

		{"Python", InstructionPreset{ID: "python", Category: instructionCode, Label: "Follow Python conventions", Content: "Follow the project's Python version, typing and formatting conventions. Use context managers for resources, preserve useful exception context and test behavior without live services."}},
		{"Python", InstructionPreset{ID: "python-environment", Category: instructionBuild, Label: "Use the project's Python environment", Content: "Use the declared Python version and existing environment and dependency tooling. Run checks within that environment, keep dependency declarations consistent, and avoid global package installation or changing tools to work around a failing check."}},
		{"Python", InstructionPreset{ID: "python-errors", Category: instructionCode, Label: "Keep Python errors and resources explicit", Content: "Catch specific exceptions at the layer that can recover and preserve their cause when adding context. Close files and clients through context managers, avoid mutable default arguments, and keep import-time work free of network requests and other unexpected side effects."}},
		{"Python", InstructionPreset{ID: "python-tests", Category: instructionTests, Label: "Test Python behavior in isolation", Content: "Use the repository's existing test framework and fixtures. Exercise invalid input, exception paths and resource cleanup with temporary files and fake services. Keep tests independent of execution order, developer credentials and the current working directory."}},

		{"JVM", InstructionPreset{ID: "jvm", Category: instructionBuild, Label: "Respect JVM lifecycles and toolchains", Content: "Use the project's configured JVM toolchain and build wrapper. Keep blocking work off UI threads, preserve cancellation and close resources through their owning lifecycle."}},
		{"JVM", InstructionPreset{ID: "jvm-contracts", Category: instructionCode, Label: "Preserve JVM nullability and public APIs", Content: "Keep nullability, serialization names and public method contracts consistent across callers. Model distinct states explicitly, propagate interruption or coroutine cancellation, and close resources in their owning scope."}},
		{"JVM", InstructionPreset{ID: "jvm-tests", Category: instructionTests, Label: "Verify the affected JVM module", Content: "Run the affected module's configured tests and static checks through its documented build entry point. Use fake services and deterministic dispatchers for asynchronous behavior; test lifecycle cleanup and rejection paths without requiring a desktop session or live provider."}},
		{"Gradle", InstructionPreset{ID: "gradle-build", Category: instructionBuild, Label: "Keep Gradle builds reproducible", Content: "Use the checked-in Gradle wrapper and declared Java toolchains where provided. Keep JVM targets and plugin versions unchanged unless the task requires an upgrade; do not commit machine-specific Java paths or generated Gradle caches."}},

		{"Rust", InstructionPreset{ID: "rust", Category: instructionCode, Label: "Preserve Rust error and ownership contracts", Content: "Preserve ownership and public error contracts. Propagate recoverable errors instead of panicking, keep unsafe code narrowly justified and run the project's documented formatting, lint and test checks."}},
		{"Rust", InstructionPreset{ID: "rust-build", Category: instructionBuild, Label: "Respect Rust workspace and feature settings", Content: "Use the repository's pinned Rust toolchain and owning Cargo package or workspace. Preserve supported feature combinations and minimum compiler requirements; avoid unrelated dependency updates and follow the repository's lockfile policy."}},
		{"Rust", InstructionPreset{ID: "rust-tests", Category: instructionTests, Label: "Test Rust failure and ownership boundaries", Content: "Exercise public APIs, error variants and resource cleanup through the existing Rust tests. Run the documented formatting, lint and test commands with the relevant feature flags, and cover unsafe or concurrency-sensitive changes with targeted regression cases."}},

		{"Shell", InstructionPreset{ID: "shell", Category: instructionCode, Label: "Make shell tooling predictable", Content: "Respect the script's declared shell, quote path and user-input expansions, propagate command failures and clean up temporary resources. Check syntax and exercise meaningful failure paths."}},
		{"Shell", InstructionPreset{ID: "shell-interface", Category: instructionCode, Label: "Preserve shell arguments and exit behavior", Content: "Keep documented arguments, exit codes and stdout/stderr contracts stable. Resolve paths relative to the script or explicit inputs rather than an assumed working directory, and pass arguments without eval or unsafe command-string construction."}},
		{"Shell", InstructionPreset{ID: "shell-tests", Category: instructionTests, Label: "Exercise shell failure and path cases", Content: "Check syntax with the script's declared shell and use the repository's existing shell checks. Test paths containing spaces, missing dependencies, failed child commands and cleanup of temporary files; do not require real credentials or production services."}},

		{"HTTP", InstructionPreset{ID: "http", Category: instructionSecurity, Label: "Protect HTTP request boundaries", Content: "Validate and bound external requests at the HTTP boundary. Preserve authentication, origin checks, cancellation and structured errors; test rejected requests without side effects."}},
		{"HTTP", InstructionPreset{ID: "http-contracts", Category: instructionProject, Label: "Coordinate API contracts and callers", Content: "Trace request decoding, domain behavior and all supported clients before changing an endpoint. Keep field names, status codes and optional-value semantics consistent; update API descriptions and contract tests alongside an intentional compatibility change."}},
		{"HTTP", InstructionPreset{ID: "http-limits", Category: instructionSecurity, Label: "Bound HTTP work and diagnostics", Content: "Keep request and response size limits, timeouts and cancellation intact. Avoid unbounded reads and automatic retries of non-idempotent work, and return useful structured errors without exposing credentials, private paths or source-bearing diagnostics."}},
		{"HTTP", InstructionPreset{ID: "http-tests", Category: instructionTests, Label: "Test HTTP rejection and side effects", Content: "Use local test servers and fake dependencies to verify successful requests, malformed input, authorization failures and timeouts. Assert status codes and response bodies, and verify that rejected or canceled requests do not perform the protected write or operation."}},

		{"SQL", InstructionPreset{ID: "sql", Category: instructionSecurity, Label: "Keep database changes safe", Content: "Parameterize database queries, keep transactions bounded and preserve rollback on failure. Follow the project's migration conventions and test data compatibility and failure paths."}},
		{"SQL", InstructionPreset{ID: "sql-migrations", Category: instructionBuild, Label: "Plan compatible database migrations", Content: "Follow the existing migration ordering and deployment procedure. Account for existing rows, constraints and older supported application versions; describe required migration steps and recovery limits instead of assuming an empty database."}},
		{"SQL", InstructionPreset{ID: "sql-tests", Category: instructionTests, Label: "Verify transactions and query behavior", Content: "Test transactions, rollback, uniqueness and null-handling against isolated fixtures using the project's database test setup. Check query plans or representative measurements before claiming a performance improvement, and keep production datasets out of tests."}},

		{"CLI", InstructionPreset{ID: "cli-contracts", Category: instructionProject, Label: "Preserve the command-line interface", Content: "Keep command names, flags, defaults and exit codes compatible unless the requested change explicitly alters them. Keep help text synchronized with behavior, validate arguments before side effects and define how non-interactive use behaves."}},
		{"CLI", InstructionPreset{ID: "cli-streams", Category: instructionCode, Label: "Keep CLI output scriptable", Content: "Keep machine-readable output on its documented stream and send progress or diagnostics to the appropriate separate stream. Preserve structured output formats, handle interrupted input and broken pipes deliberately, and avoid unsolicited prompts in non-interactive execution."}},
		{"CLI", InstructionPreset{ID: "cli-tests", Category: instructionTests, Label: "Test CLI processes end to end", Content: "Exercise argument parsing, stdout, stderr and exit status in subprocess tests with temporary directories. Cover invalid flags, missing files, interrupted execution and non-interactive input without relying on a user's shell configuration."}},

		{"Desktop", InstructionPreset{ID: "desktop-boundaries", Category: instructionSecurity, Label: "Protect the desktop host boundary", Content: "Keep native capabilities behind the existing typed bridge and authorization checks. Validate paths and external input at the host boundary; do not let rendered content or navigation silently invoke commands, access files or grant permissions."}},
		{"Desktop", InstructionPreset{ID: "desktop-lifecycle", Category: instructionUI, Label: "Tie desktop work to window and project lifecycles", Content: "Keep blocking work off the UI thread and dispose subscriptions, background tasks and terminal sessions through their owners. Reject stale responses after a project or document switch, preserve keyboard access and verify packaged assets with the supported platform build."}},

		{"Container", InstructionPreset{ID: "container-build", Category: instructionBuild, Label: "Keep container builds reproducible", Content: "Use the project's established image and dependency pinning policy. Keep the build context focused, separate build-only tools from runtime needs where the existing image design allows, and verify the documented image build without unrelated base-image upgrades."}},
		{"Container", InstructionPreset{ID: "container-secrets", Category: instructionSecurity, Label: "Keep secrets out of container layers", Content: "Do not copy credentials, local configuration or unnecessary source artifacts into images. Use the existing runtime or build-secret mechanism, preserve the configured runtime user and permissions, and check the build context and ignore rules when adding files."}},
		{"CI", InstructionPreset{ID: "ci-checks", Category: instructionTests, Label: "Keep local and CI checks aligned", Content: "Use the same maintained validation entry points locally and in CI. Preserve failure exit codes and required checks, declare platform-specific limits accurately, and keep test fixtures independent of private credentials and network-only dependencies."}},
		{"CI", InstructionPreset{ID: "ci-permissions", Category: instructionSecurity, Label: "Limit CI permissions and untrusted inputs", Content: "Keep workflow permissions limited to the job's purpose and follow the repository's action-pinning policy. Treat pull-request metadata and fork code as untrusted input; do not interpolate it into shell commands or expose privileged secrets to untrusted jobs."}},

		{"Markdown", InstructionPreset{ID: "docs", Category: instructionDocs, Label: "Keep documentation accurate", Content: "Update the existing documentation owner when behavior changes. Verify referenced paths and commands, distinguish current behavior from plans and keep examples consistent with the implementation."}},
		{"Markdown", InstructionPreset{ID: "docs-examples", Category: instructionDocs, Label: "Write usable examples and local guides", Content: "Use portable paths and placeholder credentials in examples, and verify relative links from each document's directory. Keep shared instructions in the root AGENTS.md and directory-specific details in local guides; link to an existing source of truth instead of copying it."}},
	}
}

func generalInstructionPresets() []InstructionPreset {
	return []InstructionPreset{
		{ID: "scopes", Category: instructionProject, Label: "Read the applicable AGENTS.md hierarchy", Content: "Read the root AGENTS.md and applicable directory guides before editing. Keep local rules within their directory scope, resolve conflicts using the more specific applicable guide, and follow the user's explicit task instructions. Guidance does not grant permission for unrelated actions."},
		{ID: "architecture", Category: instructionProject, Label: "Trace architecture and change ownership", Content: "Read the project overview and nearby implementations, then trace the affected entry point, state owner, callers and tests. Put the change in the layer that owns the behavior and preserve established module boundaries instead of duplicating domain rules in adapters."},
		{ID: "setup", Category: instructionBuild, Label: "Follow documented setup and check commands", Content: "Use the repository's documented setup, runtime versions and maintained build and test entry points. Run commands from their documented directory and report missing prerequisites clearly; do not invent commands or modify toolchain requirements merely to make a local check pass."},
		{ID: "dependencies", Category: instructionBuild, Label: "Keep dependency changes intentional", Content: "Reuse existing dependencies when they satisfy the requested behavior. Add or upgrade dependencies only when needed for the task, explain their purpose and compatibility impact, and update the repository's dependency metadata and lockfiles consistently."},
		{ID: "style", Category: instructionCode, Label: "Follow project conventions", Content: "Read nearby implementations before editing. Reuse existing patterns and avoid unnecessary dependencies."},
		{ID: "cancellation", Category: instructionCode, Label: "Preserve cancellation", Content: "Propagate cancellation and deadlines, reject stale asynchronous results, and own background work lifetimes."},
		{ID: "tests", Category: instructionTests, Label: "Test meaningful behavior", Content: "Cover changed behavior and meaningful error paths with deterministic tests. Report checks actually run."},
		{ID: "security", Category: instructionSecurity, Label: "Protect sensitive data", Content: "Keep credentials and source-bearing diagnostics out of logs and Git. Validate external input at its boundary."},
		{ID: "generated", Category: instructionBuild, Label: "Edit the source of generated artifacts", Content: "Identify generated code, bindings, assets and caches before editing. Change the maintained source and use the documented generator when output must be updated; do not hand-edit dependency trees, caches or generated output to hide a build failure."},
		{ID: "focused", Category: instructionWorkflow, Label: "Keep changes focused", Content: "Keep changes limited to the requested behavior. Preserve unrelated work and public contracts."},
		{ID: "review", Category: instructionWorkflow, Label: "Review every change", Content: "Prepare a diff and explain behavior and verification before explicitly approved source changes."},
		{ID: "handoff", Category: instructionWorkflow, Label: "Provide a verifiable handoff", Content: "Review the final diff, including new files, and remove unrelated changes or debug output. Summarize the resulting behavior, checks actually run and remaining limitations. Follow the repository's commit and pull-request policy; do not treat a guideline as authorization to publish or deploy."},
	}
}
