package io.miniorca.desktop

import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxHeight
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.selection.SelectionContainer
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.Button
import androidx.compose.material.ButtonDefaults
import androidx.compose.material.CircularProgressIndicator
import androidx.compose.material.MaterialTheme
import androidx.compose.material.OutlinedTextField
import androidx.compose.material.Surface
import androidx.compose.material.Text
import androidx.compose.material.darkColors
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.compose.ui.window.Window
import androidx.compose.ui.window.application
import java.io.File
import javax.swing.JFileChooser
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext

private val AppBackground = Color(0xFF0D1117)
private val Panel = Color(0xFF161B22)
private val Card = Color(0xFF21262D)
private val Border = Color(0xFF30363D)
private val PrimaryText = Color(0xFFF0F6FC)
private val SecondaryText = Color(0xFF8B949E)
private val Accent = Color(0xFF2F81F7)
private val Success = Color(0xFF3FB950)

fun main() = application {
    Window(onCloseRequest = ::exitApplication, title = "Mini-Orca", resizable = true) {
        MaterialTheme(
            colors = darkColors(
                primary = Accent,
                background = AppBackground,
                surface = Panel,
                onBackground = PrimaryText,
                onSurface = PrimaryText,
            ),
        ) {
            MiniOrcaApp()
        }
    }
}

@Composable
private fun MiniOrcaApp(api: ApiClient = remember { ApiClient() }) {
    val scope = rememberCoroutineScope()
    var project by remember { mutableStateOf<ProjectAnalysis?>(null) }
    var selected by remember { mutableStateOf<ProjectFileInfo?>(null) }
    var filter by remember { mutableStateOf("") }
    var prompt by remember { mutableStateOf("") }
    var symbol by remember { mutableStateOf("") }
    var generated by remember { mutableStateOf("") }
    var busy by remember { mutableStateOf(false) }
    var status by remember { mutableStateOf("Daemon ready") }
    var error by remember { mutableStateOf<String?>(null) }

    fun importProject() {
        val directory = chooseDirectory() ?: return
        busy = true
        error = null
        status = "Analyzing ${directory.name}…"
        scope.launch {
            runCatching { withContext(Dispatchers.IO) { api.importProject(directory.absolutePath) } }
                .onSuccess {
                    project = it
                    selected = null
                    generated = ""
                    status = "Analysis ${it.aiStatus} · ${it.analysisFile}"
                }
                .onFailure { error = it.message; status = "Import failed" }
            busy = false
        }
    }

    fun selectFile(path: String) {
        error = null
        status = "Loading $path…"
        scope.launch {
            runCatching { withContext(Dispatchers.IO) { api.fileInfo(path) } }
                .onSuccess { selected = it; generated = ""; status = path }
                .onFailure { error = it.message; status = "File load failed" }
        }
    }

    fun generate() {
        val file = selected ?: return
        if (symbol.isBlank() || prompt.isBlank()) {
            error = "Enter a function/class name and a precise request."
            return
        }
        busy = true
        error = null
        status = "Generating only $symbol in ${file.path}…"
        scope.launch {
            runCatching {
                withContext(Dispatchers.IO) { api.generate(prompt.trim(), file.path, symbol.trim()) }
            }.onSuccess {
                generated = it.output
                status = "Generated one-file result · ${it.phase}"
            }.onFailure { error = it.message; status = "Generation failed" }
            busy = false
        }
    }

    Surface(modifier = Modifier.fillMaxSize(), color = AppBackground) {
        Column {
            Header(project, busy, ::importProject)
            Row(modifier = Modifier.weight(1f).fillMaxWidth()) {
                Explorer(
                    project = project,
                    selectedPath = selected?.path,
                    filter = filter,
                    onFilter = { filter = it },
                    onSelect = ::selectFile,
                    modifier = Modifier.width(270.dp).fillMaxHeight(),
                )
                Editor(project, selected, generated, Modifier.weight(1f).fillMaxHeight())
                Generator(
                    selected = selected,
                    symbol = symbol,
                    prompt = prompt,
                    busy = busy,
                    onSymbol = { symbol = it },
                    onPrompt = { prompt = it },
                    onGenerate = ::generate,
                    modifier = Modifier.width(390.dp).fillMaxHeight(),
                )
            }
            StatusBar(status, error)
        }
    }
}

@Composable
private fun Header(project: ProjectAnalysis?, busy: Boolean, onImport: () -> Unit) {
    Row(
        modifier = Modifier.fillMaxWidth().height(56.dp).background(Panel)
            .border(BorderStroke(1.dp, Border)).padding(horizontal = 16.dp),
        verticalAlignment = Alignment.CenterVertically,
    ) {
        Box(Modifier.size(26.dp).background(Accent, RoundedCornerShape(7.dp)), contentAlignment = Alignment.Center) {
            Text("⚡", fontSize = 14.sp)
        }
        Spacer(Modifier.width(10.dp))
        Text("Mini-Orca", fontWeight = FontWeight.SemiBold)
        project?.let {
            Spacer(Modifier.width(14.dp))
            Text("/  ${it.name}", color = SecondaryText, fontSize = 13.sp)
        }
        Spacer(Modifier.weight(1f))
        if (busy) {
            CircularProgressIndicator(Modifier.size(18.dp), color = Accent, strokeWidth = 2.dp)
            Spacer(Modifier.width(12.dp))
        }
        Button(
            onClick = onImport,
            enabled = !busy,
            colors = ButtonDefaults.buttonColors(backgroundColor = Accent, contentColor = Color.White),
        ) { Text("Import project") }
    }
}

@Composable
private fun Explorer(
    project: ProjectAnalysis?,
    selectedPath: String?,
    filter: String,
    onFilter: (String) -> Unit,
    onSelect: (String) -> Unit,
    modifier: Modifier,
) {
    Column(modifier.background(Panel).border(BorderStroke(1.dp, Border)).padding(12.dp)) {
        Text("EXPLORER", color = SecondaryText, fontSize = 11.sp, fontWeight = FontWeight.Bold)
        Spacer(Modifier.height(10.dp))
        OutlinedTextField(
            value = filter,
            onValueChange = onFilter,
            placeholder = { Text("Filter files", color = SecondaryText, fontSize = 12.sp) },
            singleLine = true,
            modifier = Modifier.fillMaxWidth(),
        )
        Spacer(Modifier.height(8.dp))
        if (project == null) {
            Text("Import a project to begin.", color = SecondaryText, fontSize = 13.sp)
        } else {
            val visible = project.files.filter { filter.isBlank() || it.contains(filter, ignoreCase = true) }
            LazyColumn {
                items(visible, key = { it }) { path ->
                    val active = path == selectedPath
                    Text(
                        text = "▱  $path",
                        color = if (active) PrimaryText else SecondaryText,
                        fontFamily = FontFamily.Monospace,
                        fontSize = 12.sp,
                        modifier = Modifier.fillMaxWidth()
                            .background(if (active) Card else Color.Transparent, RoundedCornerShape(5.dp))
                            .clickable { onSelect(path) }.padding(horizontal = 8.dp, vertical = 7.dp),
                    )
                }
            }
        }
    }
}

@Composable
private fun Editor(
    project: ProjectAnalysis?,
    selected: ProjectFileInfo?,
    generated: String,
    modifier: Modifier,
) {
    Column(modifier.background(AppBackground)) {
        InfoStrip(project, selected)
        val title = when {
            generated.isNotBlank() -> "Generated preview · ${selected?.path.orEmpty()}"
            selected != null -> selected.path
            else -> "Project analysis"
        }
        Row(
            Modifier.fillMaxWidth().height(42.dp).background(Panel).border(BorderStroke(1.dp, Border))
                .padding(horizontal = 14.dp),
            verticalAlignment = Alignment.CenterVertically,
        ) { Text(title, color = SecondaryText, fontSize = 12.sp, fontFamily = FontFamily.Monospace) }

        SelectionContainer {
            Box(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(18.dp)) {
                Text(
                    text = when {
                        generated.isNotBlank() -> generated
                        selected != null -> if (selected.binary) "Binary file" else selected.content
                        project != null -> project.summary
                        else -> """Select Import project to analyze a codebase.

Mini-Orca will create .mini-orca/analysis.md and use it as project-wide context."""
                    },
                    color = PrimaryText,
                    fontFamily = if (selected != null || generated.isNotBlank()) FontFamily.Monospace else FontFamily.Default,
                    fontSize = 13.sp,
                    lineHeight = 20.sp,
                )
            }
        }
    }
}

@Composable
private fun InfoStrip(project: ProjectAnalysis?, file: ProjectFileInfo?) {
    Row(
        Modifier.fillMaxWidth().background(Panel).border(BorderStroke(1.dp, Border)).padding(10.dp),
        horizontalArrangement = Arrangement.spacedBy(8.dp),
    ) {
        if (project == null) {
            Metric("PROJECT", "Not imported", Modifier.weight(1f))
        } else {
            Metric("PROJECT", "${project.type} · ${project.fileCount} files", Modifier.weight(1f))
            Metric("SOURCE", "${project.sourceFileCount} files · ${project.totalLines} lines", Modifier.weight(1f))
            Metric("AI ANALYSIS", project.aiStatus, Modifier.weight(1f))
        }
        if (file != null) {
            Metric("SELECTED FILE", "${file.language} · ${formatBytes(file.sizeBytes)} · ${file.lineCount} lines", Modifier.weight(1f))
        }
    }
}

@Composable
private fun Metric(label: String, value: String, modifier: Modifier) {
    Column(modifier.background(Card, RoundedCornerShape(6.dp)).padding(9.dp)) {
        Text(label, color = SecondaryText, fontSize = 9.sp, fontWeight = FontWeight.Bold)
        Spacer(Modifier.height(3.dp))
        Text(value, color = PrimaryText, fontSize = 12.sp, maxLines = 1)
    }
}

@Composable
private fun Generator(
    selected: ProjectFileInfo?,
    symbol: String,
    prompt: String,
    busy: Boolean,
    onSymbol: (String) -> Unit,
    onPrompt: (String) -> Unit,
    onGenerate: () -> Unit,
    modifier: Modifier,
) {
    Column(modifier.background(Panel).border(BorderStroke(1.dp, Border)).padding(16.dp)) {
        Text("Atomic generator", fontWeight = FontWeight.SemiBold)
        Spacer(Modifier.height(4.dp))
        Text("One symbol · one file · full project context", color = SecondaryText, fontSize = 12.sp)
        Spacer(Modifier.height(18.dp))
        Text("TARGET FILE", color = SecondaryText, fontSize = 10.sp, fontWeight = FontWeight.Bold)
        Text(selected?.path ?: "Select a source file", fontFamily = FontFamily.Monospace, fontSize = 12.sp)
        Spacer(Modifier.height(14.dp))
        OutlinedTextField(
            value = symbol,
            onValueChange = onSymbol,
            label = { Text("Function or class") },
            placeholder = { Text("e.g. UserService.createUser") },
            singleLine = true,
            modifier = Modifier.fillMaxWidth(),
        )
        Spacer(Modifier.height(10.dp))
        OutlinedTextField(
            value = prompt,
            onValueChange = onPrompt,
            label = { Text("Precise change") },
            placeholder = { Text("Describe behavior, inputs, outputs, and edge cases") },
            modifier = Modifier.fillMaxWidth().height(190.dp),
        )
        Spacer(Modifier.height(12.dp))
        Text(
            "The generated preview never writes automatically. Review it before applying changes.",
            color = SecondaryText,
            fontSize = 11.sp,
        )
        Spacer(Modifier.weight(1f))
        Button(
            onClick = onGenerate,
            enabled = selected != null && symbol.isNotBlank() && prompt.isNotBlank() && !busy,
            modifier = Modifier.fillMaxWidth(),
            colors = ButtonDefaults.buttonColors(backgroundColor = Accent, contentColor = Color.White),
        ) { Text("Generate ${symbol.ifBlank { "symbol" }}") }
    }
}

@Composable
private fun StatusBar(status: String, error: String?) {
    Row(
        Modifier.fillMaxWidth().height(30.dp).background(Panel).border(BorderStroke(1.dp, Border))
            .padding(horizontal = 12.dp),
        verticalAlignment = Alignment.CenterVertically,
    ) {
        Box(Modifier.size(7.dp).background(if (error == null) Success else Color(0xFFF85149), RoundedCornerShape(50)))
        Spacer(Modifier.width(7.dp))
        Text(error ?: status, color = if (error == null) SecondaryText else Color(0xFFF85149), fontSize = 11.sp, maxLines = 1)
        Spacer(Modifier.weight(1f))
        Text("Mini-Orca v4.1.0", color = SecondaryText, fontSize = 10.sp)
    }
}

private fun chooseDirectory(): File? {
    val chooser = JFileChooser().apply {
        dialogTitle = "Import project"
        fileSelectionMode = JFileChooser.DIRECTORIES_ONLY
        isAcceptAllFileFilterUsed = false
    }
    return if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) chooser.selectedFile else null
}

private fun formatBytes(bytes: Long): String = when {
    bytes < 1024 -> "$bytes B"
    bytes < 1024 * 1024 -> "${bytes / 1024} KB"
    else -> "${bytes / (1024 * 1024)} MB"
}
